:_content-type: ASSEMBLY
:description: Working with parallelism in Serverless Workflow
:keywords: kogito, workflow, quarkus, serverless, parallelism
:navtitle: Parallelism in {product_name}
:compat-mode!:
// Metadata:
:page-aliases:

[id="assembly-working-with-parallelism"]

= Parallelism in {product_name}

This document describes how you can run parallel tasks in {product_name}.

The testing procedure described in this document is based on the `serverless-workflow-service-calls-quarkus` example application in link:{kogito_sw_examples_url}/serverless-workflow-service-calls-quarkus[GitHub repository].

[WARNING]
====
{product_name} serializes the execution of parallel tasks. Therefore, the word "parallel" does not indicate simultaneous execution, but it means that there is no logical dependency between the execution of branches. An inactive branch can start or resume the execution of a task without waiting for an active branch to be completed, in case the latter suspends the execution (for example, wait for an event reception).
====

The `serverless-workflow-service-calls-quarkus` example application is a workflow that concatenates three strings and returns a result. The concatenation in the example application is done in parallel, which includes one branch per three strings.

* <<proc-creating-parallel-workflow,Creating a parallel workflow>>
* <<proc-running-parallel-workflow,Running a parallel workflow>>
** <<proc-running-branches-in-parallel-workflow,Running some branches in parallel workflow>>

include::proc-creating-parallel-workflow.adoc[leveloffset=+1]
include::proc-running-parallel-workflow.adoc[leveloffset=+1]
include::proc-running-branches-in-parallel-workflow.adoc[leveloffset=+1]

== Additional resources

* xref:getting-started/create-your-first-workflow-service.adoc[Creating your first workflow service]

== _**Found an issue?**_

If you find an issue or any misleading information, please feel free to report it link:{docs_issues_url}[here].
We really appreciate it!

//include::../../pages/_common-content/report-issue.adoc[]
