:_content-type: CONCEPT
:description: Error definition
:keywords: kogito, workflow, serverless, error
:navtitle: Error definition
// :page-aliases:

[id="con-error-definition"]

= Error definition

An link:{spec_doc_url}#error-definition[error definition] in a workflow is composed of a `name` and `code` parameters. The `name` is a short and natural language description of an error, such as `wrong parameter`. The `code` parameter helps the implementation to identify the error.

The `code` parameter is mandatory and the engine uses different strategies to map the provided value to an exception encountered at runtime. The available strategies include fully qualified class name, error message, and status code.

Fully Qualified Class Name (FQCN)::
+
--
You can define the mapping as the fully qualified Java class name of an link:{java_exception_url}[exception type].

To determine if an exception is handled by an error definition, a workflow first checks whether or not the type of the Java exception is an instance of the exception that is specified in the error definition. Otherwise, the workflow recursively applies the same check to any embedded exception within the original Java one, till the exception chain is exhausted.

.Runtime exception examples:
[cols="50%,50%", options="header"]
|===
|Runtime exception|Error code definition
|`java.lang.RuntimeException`|`java.lang.RuntimeException`
|`java.lang.IllegalStateException`|`java.lang.RuntimeException`
|===
--

Error message::
+
--

You can define the mapping as a partial match of the error message using link:{java_regex_url}[regex] patterns.

A workflow verifies whether the message of the Java exception matches the value provided in the error `code`. The validation is performed using a regex matcher. The validation is successful if a partial match is found. Note that the validation is performed in a case-sensitive manner. If case-insensitive pattern matching is desired, use the link:{java_regex_pattern_url}[embedded flag expression] `(?i)` within the regular expression.

.Error message examples:
[cols="50%,50%", options="header"]
|===
|Error message of runtime exception|Error code definition
|`Unknown error, status code 400`|`Unknown error`
|`Unknown error, status code 400`|`(?i)Error` or `error`
|`Unknown error, status code 400`|`(.*)status code 4[0-9]\{2\}` or `status code 4[0-9]\{2\}`
|===
--

Status code::
+
--
You can define the mapping as a status code returned by the invoked service.

The external services return status codes in the event of a failure. For example, HTTP status codes are returned by REST or OpenAPI service invocations. In this case, the workflow verifies the defined error code against the HTTP code from the underlying response object.

You can define the error code either as an HTTP code or as a colon-separated string, in which the error definition contains the error code in the last part.

.Status code examples:
[cols="50%,50%", options="header"]
|===
|HTTP status code|Error code definition
|`400`|`400`
|`400`|`HTTP:400`
|===
--
