:_content-type: PROCEDURE
:description: Creating a parallel workflow
:keywords: kogito, workflow, quarkus, serverless, parallelism, parallel workflow
:navtitle: Creating a parallel workflow
:compat-mode!:
// Metadata:
:page-aliases:

[id="proc-creating-parallel-workflow"]

= Creating a parallel workflow

You can create a workflow, which performs a series of parallel tasks.

.Prerequisites

* A workflow project is created.
+
For more information about creating a workflow project, see xref:getting-started/create-your-first-workflow-service.adoc[Creating your first Serverless Workflow service].

.Procedure
. Create a workflow file named as `parallel.sw.json` under the `src/main/resources/` directory.

. Add the following content to the `parallel.sw.json` file:
+
--
.Example content for `parallel.sw.json` file
[source,json]
----
{
  "id": "parallel",
  "version": "1.0",
  "specVersion": "0.8",
  "name": "Welcome to the Parallel dimension",
  "description": "Testing parallelism",
  "start": "Parallel",
  "functions": [
    {
      "name": "concatA",
      "type": "expression",
      "operation": ".result|=.+\"A\"" <1>
    },
    {
      "name": "concatB",
      "type": "expression",
      "operation": ".result|=.+\"B\"" <2>
    },
    {
      "name": "concatC",
      "type": "expression",
      "operation": ".result|=.+\"C\"" <3>
    }
  ],
  "states": [
    {
      "name": "Parallel",
      "type": "parallel", <4>
      "branches": [ <5>
        {
          "name": "branchA",
          "actions": [
            {
              "functionRef": "concatA" <6>
            }
          ]
        },
        {
          "name": "branchB",
          "actions": [
            {
              "functionRef": "concatB" <7>
            }
          ]
        },
        {
          "name": "branchC",
          "actions": [
            {
              "functionRef": "concatC" <8>
            }
          ]
        }
      ],
      "completionType": "allOf", <9>
      "end": {
        "terminate": true
      }
    }
  ]
}
----

<1> Function that concatenates the string `A`.
<2> Function that concatenates the string `B`.
<3> Function that concatenates the string `C`.
<4> Defines the type of the state as `parallel`.
<5> Defines the branches that run in parallel.
<6> Defines the function that runs in `branchA`.
<7> Defines the function that runs in `branchB`.
<8> Defines the function that runs in `branchC`.
<9> Defines the completion type of the parallel state as `allOf`. This means that the parallel state is completed when all the branches are completed.
--
