:_content-type: PROCEDURE
:description: Running some branches in parallel workflow
:keywords: kogito, workflow, quarkus, serverless, parallelism, branches
:navtitle: Running some branches in parallel workflow
:compat-mode!:
// Metadata:
:page-aliases:

[id="proc-running-branches-in-parallel-workflow"]

= Running some branches in parallel workflow

You can define the `"completionType": "atLeast"` to run only some branches in parallel workflow, instead of defining `"completionType": "allOf"`. When you define `"completionType": "atLeast"`, you also need to define the minimum number of branches that you want to run by defining the `"numCompleted":` property.

.Prerequisites

* A parallel workflow is created.
+
For more information, see <<proc-parallel-creating-the-workflow, Creating a parallel workflow>>.

.Procedure
. Change the `completionType` property to `"atLeast"` and add the `"numCompleted": 2` property to the parallel state.
+
--
.Example parallel workflow
[source,json]
----
{
  "id": "parallel",
  "version": "1.0",
  "specVersion": "0.8",
  "name": "Welcome to the Parallel dimension",
  "description": "Testing parallelism",
  "start": "Parallel",
  "functions": [
    {
      "name": "concatA",
      "type": "expression",
      "operation": ".result|=.+\"A\""
    },
    {
      "name": "concatB",
      "type": "expression",
      "operation": ".result|=.+\"B\""
    },
    {
      "name": "concatC",
      "type": "expression",
      "operation": ".result|=.+\"C\""
    }
  ],
  "states": [
    {
      "name": "Parallel",
      "type": "parallel",
      "branches": [
        {
          "name": "branchA",
          "actions": [
            {
              "functionRef": "concatA"
            }
          ]
        },
        {
          "name": "branchB",
          "actions": [
            {
              "functionRef": "concatB"
            }
          ]
        },
        {
          "name": "branchC",
          "actions": [
            {
              "functionRef": "concatC"
            }
          ]
        }
      ],
      "completionType": "atLeast", <1>
      "numCompleted": "2", <2>
      "end": {
        "terminate": true
      }
    }
  ]
}
----
<1> Defines the completion type of the parallel state as `atLeast`.
<2> Defines the minimum number of branches that you want to run. This means that the parallel state is completed when at least two branches are completed.
--

. To run the created parallel workflow, send a request to the `/parallel` endpoint as shown in the following example:
+
--
.Example request
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8080/parallel' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{}'
----

.Example response
[source,shell]
----
{"id":"3da62df1-c4e7-48c9-a3e4-7f63872c92f4","workflowdata":{"result":"BC"}}
----

[NOTE]
====
The `"result":"BC"` in the response might be different in each request.
====

The parallel workflow data shows the concatenated string as result, but in this case, the workflow concatenates only two letters.
--
