= Workflow plugin for Knative CLI
06-30-2022
:compat-mode!:
// Metadata:
:description: Overview of the Workflow plugin for the Knative CLI
:keywords: kogito, workflow, serverless, knative, plugin

The `kn-plugin-workflow` is a plugin for the Knative Client to enable users to quickly set up a local Kogito Serverless Workflow project from the command line.

.Prerequisites
* link:{java_install_url}[Java] at least version {java_min_version}
* link:{maven_install_url}[Maven] at least version {maven_min_version}
* link:{docker_install_url}[Docker] (Optional)
* link:{podman_install_url}[Podman] (Optional)
* link:{kubectl_install_url}[Kubernetes CLI].

== Installation

You can download the latest binaries from the link:{kie_tools_releases_page_url}[KIE Tooling Releases] page.

There are two ways to run `kn workflow`:

. You can run it standalone, just put it on your system path and make sure it is executable.
. You can install it as a plugin of the `kn` client to run:
* Follow the link:{kn_cli_install_url}[documentation] to install `kn` CLI if you don't have it.
* Copy the `kn-workflow` binary to a directory on your `PATH` (for example, `/usr/local/bin`) and make sure its filename is `kn-workflow`.
* On macOS give the ownership to the root user:
`sudo chown root: /usr/local/bin/kn-workflow`
* Run `kn plugin list` to verify that the `kn-workflow` plugin is installed successfully.

After installing the plugin, you can use `kn workflow` to run its related subcommands.

== Usage
After the installation, you will be able to use the `workflow` subcommand in the Knative CLI. It's possible to use in two ways:

[source,shell]
----
kn workflow
kn-workflow
----

The following help message will appear after running the command above:
[source,text]
----
Manage Kogito Serverless Workflow projects

Usage:
  kn workflow [command]

Available Commands:
  build       Build a Kogito Serverless Workflow project and generate a container image
  completion  Generate the autocompletion script for the specified shell
  create      Create a Kogito Serverless Workflow project
  deploy      Deploy a Kogito Serverless Workflow project
  help        Help about any command

Flags:
  -h, --help      help for kn-workflow
  -v, --verbose   Print verbose logs

Use "kn workflow [command] --help" for more information about a command.
----

=== Create
The `create` command scaffolds a new Kogito Serverless Workflow project in the current directory.

It sets up a Quarkus project with minimal extensions to build a Kogito Serverless Workflow project. Also, the generated project has a "hello world" workflow.sw.json located on the
`./<project-name>/src/main/resources` directory.

.Creates a new project called "new-project"
[source,shell]
----
kn workflow create
----

By default, the generated project is named "new-project". This name can be overwritten with the `[-n|--name]` flag.

.Creates a new project called "my-project"
[source,shell]
----
kn workflow create --name my-project
----

Also, it's possible to add more extensions to the Quarkus project during its creation by using the `[-e|--extension]` flag. You can pass more than one extension, but they need to be separated by a comma.

.Creates a new project with "quarkus-jsonp" and "quarkus-smallrye-openapi" extensions
[source,shell]
----
kn workflow create --extension quarkus-jsonp,quarkus-smallrye-openapi
----

[NOTE]
====
The first time you use the `create` command, it can take a while due to the necessity to download all dependencies for the Quarkus project.
====

=== Build
The `build` command builds a Kogito Serverless Workflow project in the current directory and generates a container image. The build process produces a `knative.yml` deploy file in the `./target/kubernetes` folder. If your workflow has **events**, it'll also generate a `kogito.yml` deploy file.

To use the the `build` you need to provide at least one of the two flags: `--image` or `--image-name`.

.Builds the project and generates a local image called "quay.io/my-project"
[source,shell]
----
kn workflow build --image my-project
kn workflow build --image-name my-project
----
NOTE: The "registry" and "tag" defaults are "quay.io" and "latest" respectively.

==== Image naming options
Let's take a better look at the image naming options.

The `[-i|--image]` flag can be used in several ways.

* --image=[name]
* --image=[name]:[tag]
* --image=[repository]/[name]
* --image=[repository]/[name]:[tag]
* --image=[registry]/[repository]/[name]
* --image=[registry]/[repository]/[name]:[tag]

Also, it's possible to use specific flags to compose the image's full name.

* --image-registry
* --image-repository
* --image-name
* --image-tag

[NOTE]
====
If the "--image" flag is provided together with any of these flags, the specific value will override "--image".
====

.Builds the project and generates a local image called "quay.io/other-user/my-project:1.0.1"
[source,shell]
----
kn workflow build --image my-user/my-project:1.0.0 --image-repository other-user --image-tag 1.0.1
----

==== Building strategy
We have two different strategies to build the project and generate the image.

.Jib
Jib is an extension that enables building a container image without the necessity of a container runtime. Rebuilds are fast, and the resultant image is optimized.

.Builds the project and generates a local image using Jib (Save it in the Docker runtime)
[source,shell]
----
kn workflow build --image my-project --jib
----

.Builds the project and generates a local image using Jib (Save it in the Podman runtime)
[source,shell]
----
kn workflow build --image my-project --jib-podman
----

If you don't want to use any container runtime, use the `--push` option, so the built image will be immediately pushed to the respective registry.

.Builds the project and pushes the image using Jib (No container runtime required)
[source,shell]
----
kn workflow build --image my-project --jib --push
----

[NOTE]
====
Remember to have access to your registry before using the "--push" option. You can do it using the "docker login", "podman login", or any other equivalent method.
====

.Docker

Building with Docker is straightforward as it's the default option. Also, it's possible to automatically push the image to the respective registry by using the `--push` option.

.Builds the project and pushes the image using Docker
[source,shell]
----
kn workflow build --image my-project --push
----

=== Deploy
The `deploy` command deploys a Kogito Serverless Workflow project in the current directory (build command is required). It uses the `./target/kubernetes` folder to find the generated `knative.yml` and, if exists, the `kogito.yml`. If your deployment files are saved in another folder, it's possible to override the path with the `--path` flag.

Also, remember to have access to your cluster, and your cluster needs to have access to your image.

.Deploys the project to authenticated cluster
[source,shell]
----
kn workflow deploy
kn workflow deploy --path other-path
----

[NOTE]
====
If you need to use a more complex deploy setup, we recommend directly using the "kubectl" command line.
====

== Building from Source
If you want to build the project from source, follow the steps:
[source,shell]
----
git clone git@github.com:kie-group/kie-tools.git
cd kie-tools
pnpm bootstrap
pnpm -F @kie-tools/kn-plugin-workflow... build:dev
cd packages/kn-plugin-workflow
go mod tidy
----

include::../../pages/_common-content/report-issue.adoc[]
