= Basic Integration Test with REST Assured
// Metadata:
:description: Basic Integration Test with REST Assured
:keywords: kogito, workflow, quarkus, serverless, quarkus-cli, test, restassured

As a developer, you can use https://rest-assured.io/[REST Assured] to test your Serverless Workflow application.

You can directly access an example application by cloning `kogito-quarkus-examples/serverless-workflow-testing-with-rest-assured`
from the https://github.com/kiegroup/kogito-examples.git[Kogito Examples] GitHub repository.

This guide describes how to test the Serverless Workflow application that exposes the `hello` endpoint.
The endpoint expects a `name` as a parameter and returns a `greeting`.

Example: For a request with the given body:

[source,json]
----
{
  "workflowdata": {
    "name": "John Doe"
  }
}
----

The endpoint should return a response with a body similar to:

[source,json]
----
{
  "id": "00ce5c1d-4936-4e18-998c-f5c5d5d784ad",
  "workflowdata": {
    "greeting": "Hello, John Doe"
  }
}
----

[[testing-application]]
== Testing the Serverless Workflow application

Follow the procedure below to create a test to check if the `hello` endpoint returns the proper greeting for a given `name`.

.Procedure
. Before creating the test, check if the `pom.xml` contains the required dependencies:
+
--

[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-junit5</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>io.rest-assured</groupId>
    <artifactId>rest-assured</artifactId>
    <scope>test</scope>
</dependency>
----
--

. Create a test class named `HelloTest` in the `src/test/java/org/kie/kogito/examples/`
directory with the following content:
+
--
.src/test/java/org/kie/kogito/examples/HelloTest.java
[source,java]
----
package org.kie.kogito.examples;

import io.quarkus.test.junit.QuarkusTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

@QuarkusTest
class HelloTest {

    @BeforeAll
    static void init() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails(); <1>
    }

    @Test
    void testHello() {
        given()
                .contentType(ContentType.JSON) <2>
                .accept(ContentType.JSON) <3>
                .body("{\"workflowdata\": {\"name\": \"John Doe\"}}") <4>
                .when()
                .post("/hello") <5>
                .then()
                .statusCode(201) <6>
                .body("workflowdata.greeting", equalTo("Hello, John Doe")); <7>
    }
}
----

<1> Enables logging of the request and response when the test fails.
<2> Defines JSON as the content type of the request.
<3> Specifies the `accept` header of the request. This is a shortcut for: `header("Accept", "application/json")`.
<4> Defines the request body as: `{"workflowdata": {"name": "John Doe"}}`.
<5> Specifies the request as a POST to the `/hello` URL.
<6> Defines `201` as the expected response status code.
<7> Defines that `Hello, John Doe` is expected in the `workflowdata.greeting` JSON path.

--

. Run your test by running the following Maven command:

+
--
[source,shell]
----
mvn clean verify
----

You should see an output similar to:

[source,shell]
----
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.kie.kogito.examples.HelloTest
2022-06-03 16:36:11,461 INFO  [org.jbo.threads] (main) JBoss Threads version 3.4.2.Final
2022-06-03 16:36:11,708 INFO  [org.kie.kog.cod.api.uti.AddonsConfigDiscovery] (build-1) Performed addonsConfig discovery, found: AddonsConfig{usePersistence=false, useTracing=false, useMonitoring=false, usePrometheusMonitoring=false, useCloudEvents=true, useExplainability=false, useProcessSVG=false, useEventDrivenDecisions=false, useEventDrivenRules=false}
2022-06-03 16:36:12,004 INFO  [org.kie.kog.cod.cor.uti.ApplicationGeneratorDiscovery] (build-9) Generator discovery performed, found [processes]
2022-06-03 16:36:14,486 INFO  [org.kie.kog.add.qua.mes.com.QuarkusKogitoExtensionInitializer] (main) Registered Kogito CloudEvent extension
2022-06-03 16:36:14,612 INFO  [io.quarkus] (main) serverless-workflow-testing-with-rest-assured 1.0 on JVM (powered by Quarkus 2.9.2.Final) started in 3.635s. Listening on: http://localhost:8081
2022-06-03 16:36:14,613 INFO  [io.quarkus] (main) Profile test activated.
2022-06-03 16:36:14,613 INFO  [io.quarkus] (main) Installed features: [cache, cdi, jackson-jq, kogito-addon-messaging-extension, kogito-processes, kogito-serverless-workflow, reactive-routes, rest-client, rest-client-jackson, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-reactive-messaging, smallrye-reactive-messaging-http, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.819 s - in org.kie.kogito.examples.HelloTest
2022-06-03 16:36:16,559 INFO  [io.quarkus] (main) serverless-workflow-testing-with-rest-assured stopped in 0.028s
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ serverless-workflow-testing-with-rest-assured ---
[INFO] Building jar: /home/helber/dev/kiegroup/kogito-examples/kogito-quarkus-examples/serverless-workflow-testing-with-rest-assured/target/serverless-workflow-testing-with-rest-assured-1.0.jar
[INFO]
[INFO] --- quarkus-maven-plugin:2.9.2.Final:build (default) @ serverless-workflow-testing-with-rest-assured ---
[INFO] Performed addonsConfig discovery, found: AddonsConfig{usePersistence=false, useTracing=false, useMonitoring=false, usePrometheusMonitoring=false, useCloudEvents=true, useExplainability=false, useProcessSVG=false, useEventDrivenDecisions=false, useEventDrivenRules=false}
[INFO] Generator discovery performed, found [processes]
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2669ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.558 s
[INFO] Finished at: 2022-06-03T16:36:19-03:00
[INFO] ------------------------------------------------------------------------
----
--

== Additional resources

* xref:testing-and-troubleshooting/mocking-opnapi-services-with-wiremock.adoc[Mocking OpenAPI services with WireMock]
* xref:testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc[Mocking HTTP CloudEvents with WireMock]
* xref:testing-and-troubleshooting/integration-tests-with-postgresql.adoc[Integration tests with PostgreSQL]
* link:https://quarkus.io/guides/getting-started-testing[Testing a Quarkus Application].
* link:https://rest-assured.io/#docs[REST Assured Documentation].