= {product_name} plug-in for Knative CLI

:compat-mode!:
// Metadata:
:description: Overview of the Workflow plugin for the Knative CLI
:keywords: kogito, workflow, serverless, knative, plugin
// links
:apple_support_url: https://support.apple.com/guide/mac-help/mh40616/mac

{product_name} provides a plug-in named `kn-plugin-workflow` for Knative CLI, which enables you to set up a local workflow project quickly using the command line.

This document describes how you can install and use the `kn-plugin-workflow` plug-in in {product_name}.

[[proc-install-sw-plugin-kn-cli]]
== Installing the {product_name} plug-in for Knative CLI

You can use the {product_name} plug-in to set up your local workflow project quickly using Knative CLI. 

.Prerequisites
* link:{java_install_url}[Java] {java_min_version} is installed.
* link:{maven_install_url}[Maven] {maven_min_version} or later is installed.
* (Optional) link:{docker_install_url}[Docker] is installed.
* (Optional) link:{podman_install_url}[Podman] is installed.
* link:{kubectl_install_url}[Kubernetes CLI] is installed.

.Procedure
. Download the latest binaries from the link:{kie_tools_releases_page_url}[KIE Tooling Releases] page.
. Run the `kn workflow` command using one of the following methods:
+
--
* Add `kn workflow` command in your system path and ensure that it is executable.
* Install `kn workflow` command as a plug-in of the Knative CLI using the following steps:
.. Install the Knative CLI. For installation instructions, see link:{kn_cli_install_url}[Installing kn] documentation.
.. Copy the `kn-workflow` binary to a directory in your `PATH`, such as `/usr/local/bin` and ensure that the file name is `kn-workflow`.
.. On Mac, add execution permission as follows:
+
`chmod +x /usr/local/bin/kn-workflow`
+
[WARNING]
==== 
Some systems might block the application to run due to Apple enforcing policies. To fix this problem, check the *Security & Privacy* section in the *System Preferences* -> *General* tab to approve the application to run. For more information, see link:{apple_support_url}[Apple support article: Open a Mac app from an unidentified developer].
====
.. Run the following command to verify that `kn-workflow` plug-in is installed successfully:
+
`kn plugin list`

After installing the plug-in, you can use `kn workflow` to run the related subcommands.
--

. Use the `workflow` subcommand in Knative CLI as follows:
+
--
.Methods to use workflow subcommand
[source,shell]
----
kn workflow
kn-workflow
----

.Example output
[source,text]
----
Manage SonataFlow projects

Usage:
  kn workflow [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  create      Creates a new SonataFlow project
  deploy      Deploy a SonataFlow project on Kubernetes via SonataFlow Operator
  help        Help about any command
  quarkus     Manage SonataFlow projects built in Quarkus
  run         Run a SonataFlow project in development mode
  undeploy    Undeploy a SonataFlow project on Kubernetes via SonataFlow Operator
  version     Show the version

Flags:
  -h, --help      help for kn
  -v, --version   version for kn

Use "kn [command] --help" for more information about a command.
----
--

[[proc-create-sw-project-kn-cli]]
== Creating a workflow project using Knative CLI

After installing the {product_name} plug-in, you can use the `create` command with `kn workflow` to scaffold a new workflow project in your current directory.

The `create` command sets up {product_name} project containing minimal a "hello world" `workflow.sw.json` file in your `./<project-name>` directory.

.Prerequisites
* {product_name} plug-in for Knative CLI is installed.
+
For more information about installing the plug-in, see <<proc-install-sw-plugin-kn-cli, Installing the {product_name} plug-in for Knative CLI>>.
ifeval::["{kogito_version_redhat}" != ""]
* You followed the steps in xref:getting-started/create-your-first-workflow-service.adoc#proc-configuring-maven-rhbq[Configuring your Maven project to Red Hat build of Quarkus and OpenShift Serverless Logic]
endif::[]

.Procedure
. In Knative CLI, enter the following command to create a new project:
+
--
.Creates a project named `new-project`
[source,shell]
----
kn workflow create
----

By default, the generated project is named as `new-project`. You can overwrite the project name by using the `[-n|--name]` flag as follows:

.Create a project named `my-project`
[source,shell]
----
kn workflow create --name my-project
----
--

[[proc-build-sw-project-kn-cli]]
== Running a workflow project using Knative CLI

After creating your workflow project, you can use the `run` command with `kn workflow` to build & run your workflow project in your current directory. 

This will start a {product_name} docker image and map your local folder to this image.

.Prerequisites
* {product_name} plug-in for Knative CLI is installed.
+
For more information about installing the plug-in, see <<proc-install-sw-plugin-kn-cli, Installing the {product_name} plug-in for Knative CLI>>.

* A workflow project is created.
+
For more information about creating a workflow project, see <<proc-create-sw-project-kn-cli, Creating workflow project using Knative CLI>>.

.Procedure
. In Knative CLI, enter the following command to build and run your workflow project:
+
--
.Run the project and start a local development image`
[source,shell]
----
kn workflow run
----
--
. Navigate to `localhost:8080/q/dev` to access the Development UI locally.

[[proc-deploy-sw-project-kn-cli]]
== Deploying a workflow project using Knative CLI

You can use the `deploy` command combined with `kn workflow` to deploy your workflow project in your current directory. 

.Prerequisites
* {product_name} plug-in for Knative CLI is installed.
+
For more information about installing the plug-in, see <<proc-install-sw-plugin-kn-cli, Installing the {product_name} plug-in for Knative CLI>>.

* A workflow project is created.
+
For more information about created a workflow project, see <<proc-create-sw-project-kn-cli, Creating workflow project using Knative CLI>>.

* A workflow project is built.
+
For more information about building your workflow project, see <<proc-build-sw-project-kn-cli, Building workflow project using Knative CLI>>.

.Procedure
. In Knative CLI, enter the following command to deploy your workflow project:
+
--
.Deploy a workflow project
[source,shell]
----
kn workflow deploy
----

.Deploy a workflow project using `--path`
[source,shell]
----
kn workflow deploy --path other-path
----

Also, ensure that you have access to your cluster and your cluster can access the generated container image.

[NOTE]
====
You can use the `kubectl` command line if you want to use a complex deployment setup for your workflow project.
====
--

== Additional resources

* xref:getting-started/create-your-first-workflow-service.adoc[Creating your first workflow service]

include::../../pages/_common-content/report-issue.adoc[]
