Mocking OpenAPI services with WireMock
======================================
// Metadata:
:description: Mocking OpenAPI services with WireMock
:keywords: kogito, workflow, quarkus, serverless, quarkus-cli, test, wiremock, openapi
// links:
:wiremock_url: https://wiremock.org/docs/
:quarkus_test_resource_url: https://quarkus.io/guides/getting-started-testing#quarkus-test-resource
// Referenced documentation pages.
:getting-familiar-with-our-tooling: xref:getting-started/getting-familiar-with-our-tooling.adoc
:create-your-first-workflow-service: xref:getting-started/create-your-first-workflow-service.adoc
:orchestration-of-openapi-based-services: xref:service-orchestration/orchestration-of-openapi-based-services.adoc

This document describes how to mock OpenAPI services using WireMock. The testing procedure in this document is based on the `serverless-workflow-examples/serverless-workflow-service-calls-quarkus` example application. You can access this example application in the link:{kogito_sw_examples_url}/serverless-workflow-service-calls-quarkus[GitHub repository].

== Prerequisites

The examples in this document assumes that you have the following prerequisites:

* You have installed the {getting-familiar-with-our-tooling}[Kogito tooling].

* You have {create-your-first-workflow-service}[created a Serverless Workflow project] that {orchestration-of-openapi-based-services}[orchestrates OpenAPI services].

== About WireMock

{wiremock_url}[WireMock] is an open source Mocking API for unit, integration and performance tests. You can use it to isolate your tests from 3rd party APIs and prototype APIs that still don't exist.

== Adding a mocked OpenAPI service to your tests

The following procedure describes how to add WireMock to your Serverless Workflow application:

.Procedure

. Add the WireMock dependency to your `pom.xml` file.

+
--
.WireMock dependency
[source,xml]
----
<dependency>
    <groupId>com.github.tomakehurst</groupId>
    <artifactId>wiremock-jre8</artifactId>
    <version>{wiremock.version}</version>
    <scope>test</scope>
</dependency>
----

[NOTE]
====
Replace `{wiremock.version}` with the version of WireMock you want to use.
====
--

. Choose when you want to start your WireMock server. There are two options:

* Start WireMock server as a `QuarkusTestResource`. This means that your WireMock server will be started once before to run any test and will be stopped once the tests finishes. This is the option that fits most use cases.
* Start a WireMock server independently for each test. This is useful if you need different behavior for each test.

. Define how the WireMock server should be started.

+
--
.Starting a WireMock server example
[source,java]
----
WireMockConfiguration config = WireMockConfiguration.wireMockConfig().dynamicPort(); <1>
WireMockServer wireMockServer = new WireMockServer(config); <2>
wireMockServer.start(); <3>
----
<1> Creates the configuration for the WireMock server. It's a good practice to use a dynamic port when possible. This way, you prevent the tests from failing due to port conflicts. When using a dynamic port is not possible, you can use the `WireMockConfiguration#port(int)` method to use a fixed port number.
<2> Creates the WireMock server instance.
<3> Starts the WireMock server.
--

. Mock the endpoints.

+
--
.Mocking endpoints example
[source,java]
----
ObjectMapper objectMapper = new ObjectMapper();
JsonNode greecePayload = objectMapper.readTree(getClass().getResourceAsStream("/country_mock.json")); <1>

wireMockServer.stubFor(WireMock.get(WireMock.urlEqualTo("/rest/v2/name/Greece")) <2>
                               .willReturn(WireMock.aResponse() <3>
                                                   .withStatus(200) <4>
                                                   .withHeader("Content-Type", "application/json") <5>
                                                   .withJsonBody(greecePayload))); <6>
----
<1> Creates the JSON payload that will be returned by the WireMock server. Alternatively, you can use the `ResponseDefinitionBuilder#withBody` method to define a `String` or a `byte[]` as the response body.
<2> Defines a stub for the `/rest/v2/name/Greece` endpoint.
<3> Defines the response for the stub.
<4> Defines the response status.
<5> Defines the response headers.
<6> Defines the response body.
--

. Stop the WireMock server.

+
--
.Stopping a WireMock server example
[source,java]
----
wireMockServer.stop();
----
--

=== Starting a WireMock server as a `QuarkusTestResource`

The following procedure describes how to start a WireMock server as a `QuarkusTestResource`.

.Procedure

. Create a class that implements the `QuarkusTestResource` interface.

+
--
.QuarkusTestResource implementation example
[source,java]
----
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.Map;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;

public class RestCountriesMockServer implements QuarkusTestResourceLifecycleManager {

    private WireMockServer wireMockServer;

    @Override
    public Map<String, String> start() { <1>
        configureWiremockServer();
        return Map.of("quarkus.rest-client.restcountries_json.url", wireMockServer.baseUrl() + "/rest"); <2>
    }

    private void configureWiremockServer() {
        wireMockServer = new WireMockServer(WireMockConfiguration.wireMockConfig().dynamicPort());
        wireMockServer.start();

        ObjectMapper objectMapper = new ObjectMapper();
        JsonNode greecePayload;
        try {
            greecePayload = objectMapper.readTree(getClass().getResourceAsStream("/country_mock.json"));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        wireMockServer.stubFor(get(urlEqualTo("/rest/v2/name/Greece"))
                                       .willReturn(aResponse()
                                                           .withStatus(200)
                                                           .withHeader("Content-Type", "application/json")
                                                           .withJsonBody(greecePayload)));
    }

    @Override
    public void stop() { <3>
        if (wireMockServer != null) {
            wireMockServer.stop();
        }
    }
}
----
<1> Start the test resource. This method is called once before all tests.
<2> Returns a map of application properties that will be set in the test environment. In this case, it sets the `quarkus.rest-client.restcountries_json.url` property to the base URL of the WireMock server.
<3> Stop the test resource. This method is called once after all tests.
--

. Use the `QuarkusTestResource` implementation in your test class.

+
--
.Example of a test class using the `QuarkusTestResource` implementation
[source,java]
----
import io.quarkus.test.common.QuarkusTestResource;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

@QuarkusTest
@QuarkusTestResource(RestCountriesMockServer.class) <1>
class CountryServiceWorkflowTest {

    @Test
    void testFeatureA() {
        // ...
    }

    @Test
    void testFeatureB() {
        // ...
    }
}
----
<1> Uses the `RestCountriesMockServer` class as a test resource.
--

+
--
For more information about `QuarkusTestResource`, see {quarkus_test_resource_url}[Starting services before the Quarkus application starts].
--

=== Starting a WireMock server to be used in a specific test

The following procedure describes how to start a WireMock server to be used in a specific test.

.Procedure

. Wrap the test logic between starting and stopping the WireMock server.

+
--
.Example of a test using a specific WireMock server instance
[source,java]
----
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.core.WireMockConfiguration;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.get;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;

@QuarkusTest
class CountryServiceWorkflowTest {

    @Test
    void testFeatureA() throws IOException {
        WireMockServer wireMockServer = startWiremockServerForFeatureA();
        try {
            // test logic
        } finally {
            wireMockServer.stop();
        }
    }

    @Test
    void testFeatureB() {
        WireMockServer wireMockServer = startWiremockServerForFeatureB();
        try {
            // test logic
        } finally {
            wireMockServer.stop();
        }
    }

    private static WireMockServer startWiremockServerForFeatureA() throws IOException {
        WireMockServer wireMockServer = new WireMockServer(WireMockConfiguration.wireMockConfig().dynamicPort());
        wireMockServer.start();

        ObjectMapper objectMapper = new ObjectMapper();
        JsonNode greecePayload = objectMapper.readTree(CountryServiceWorkflowTest.class.getResourceAsStream("/country_mock_feature_a.json"));
        wireMockServer.stubFor(get(urlEqualTo("/rest/v2/name/Greece"))
                                       .willReturn(aResponse()
                                                           .withStatus(200)
                                                           .withHeader("Content-Type", "application/json")
                                                           .withJsonBody(greecePayload)));

        return wireMockServer;
    }

    private static WireMockServer startWiremockServerForFeatureB() {
        WireMockServer wireMockServer = new WireMockServer(WireMockConfiguration.wireMockConfig().dynamicPort());
        wireMockServer.start();

        wireMockServer.stubFor(get(urlEqualTo("/rest/v2/name/Greece"))
                                       .willReturn(aResponse().withStatus(404)));

        return wireMockServer;
    }
}
----
--

== Testing your Serverless Workflow application

To test your Serverless Workflow application, you can follow the instructions in the xref:testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc[Basic Integration Test with RestAssured] guide.

include::../../pages/_common-content/report-issue.adoc[]