github:
  description: Apache KIE SonataFlow documentation repository
  homepage: https://kie.apache.org
  labels:
    - apache
    - java
    - workflow
    - workflow-engine
    - spring-boot
    - quarkus
    - kogito
    - knative
    - cloud-native
    - cloudevents
    - kubernetes
    - hacktoberfest
    - persistence
    - data-index
    - jobs-service
  ghp_branch:  gh-pages
  ghp_path:    /
  features:
    issues: true
