= Kogito Documentation and Guides

== Prerequisite

Running Antora with Lunr extension (required to generate self-hosted search) requires Node.js v16.0.0 or above.

== Installing Dependencies

This folder contains `package.json` files that you can use to install dependencies. Run the following command.

`npm install`

== Building the website locally

This folder contains an antora playbook, `antora-playbook-author.yml` to generate the documentation. To run and generate the documentation locally under the `build` folder use:

`npx antora antora-playbook-author.yml`

== How it works

This module builds a documentation website using https://antora.org/[Antora].

To simplify the maintenance, the documentation website is based on a pre-built default Antora UI bundle
located in `ui-bundle/ui-bundle.zip`. Customizations are located in `supplemental-ui` that Antora uses to replace
parts of the default `ui-bundle.zip`.

== How to upgrade

=== Upgrade UI bundle

Download the latest `ui-bundle.zip` from https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable[Antora GitLab job]
and replace the existing one in the `ui-bundle` directory.

Be aware that the bundle is not versioned and in the future might not be compatible with the customizations this website uses.
