= Deploying your {product_name} application on OpenShift
:compat-mode!:
// Metadata:
:description: Deploying Serverless Application on Minikube
:keywords: kogito, workflow, quarkus, serverless, kn, oc, openshift
:table-caption: Data Set
// envs for common content
:registry: OpenShift's
:cluster_kind: OpenShift with Red Hat OpenShift Serverless is ready
:k8s_registry: image-registry.openshift-image-registry.svc:5000
:knative_procedure: link:https://docs.openshift.com/serverless/1.28/install/installing-knative-eventing.html[Knative Eventing]
:default_namespace: kogito-serverless
:command_line_tool: oc
:command_line_tool_name: OpenShift CLI
:quarkus-k8s-plugin: quarkus-openshift
:platform: OpenShift
:container_push: This property should be removed if deploying on OpenShist Clusters
// links
:ocp_local_url_install: https://access.redhat.com/documentation/en-us/red_hat_openshift_local/2.17/html/getting_started_guide/installation_gsg
:ocp_cli_url: https://docs.openshift.com/container-platform/4.12/cli_reference/openshift_cli/getting-started-cli.html#cli-about-cli_cli-developer-commands
:ocp_swf_install_url: https://docs.openshift.com/serverless/1.29/install/install-serverless-operator.html
:ocp_expose_registry_url: https://docs.openshift.com/container-platform/4.12/registry/securing-exposing-registry.html
:knative_istio_issue_url: https://access.redhat.com/solutions/4791871


This document describes how to deploy a {product_name} application using a OpenShift cluster, along with a procedure to run the OpenShift Serverless Operator, which is based on Knative.

.Prerequisites
* Your xref:cloud/quarkus/build-workflow-image-with-quarkus-cli.adoc[{product_name} application] is ready to use.
* link:{ocp_cli_url}[OpenShift CLI] is installed.
* link:{ocp_kn_cli_url}[Knative CLI] is installed.
* xref:tooling/kn-plugin-workflow-overview.adoc[Knative CLI workflow plugin] is installed.
* link:{podman_install_url}[Podman] +
If you are using link:{docker_install_url}[Docker], you might need to update the commands accordingly.
* (Optional) link:{quarkus_cli_url}[Quarkus CLI] is installed.

For the following steps we will be using the link:{ocp_local_url}[OpenShift Local]. However, the steps described here can be used on any OpenShift 4.x version that has support for OpenShift Serverless.

[[proc-install-openshift-local]]
== Installing OpenShift Local

_If you already have an OpenShift cluster available you can skip this section._

Instructions to install Openshift Local can be found {ocp_local_url_install}[here]._

Once you have OpenShift Local running, proceed to the next topic.
[IMPORTANT]
====
If you are running OpenShift Local on Mac with M1 processors, you might not find the OpenShift Serverless Operator available.
====

Before proceeding further, make sure that you have access to the OpenShift cluster with Serverless available and the OpenShift Serverless operator is properly installed. To do this, please follow these link:{ocp_swf_install_url}[steps].


[TIP]
====
If you get error messages related to `Istio`, this link:{knative_istio_issue_url}[article] might be helpful.
====


[[proc-deploy-sw-application-openshift]]
== Deploying your workflow application on OpenShift

Once `Knative Serving` is ready, you can initiate the process of deploying your {product_name} application on OpenShift.

// shared app req
include::../common/_deploy_workflow_application_requisites.adoc[]

. After checking the prerequisites, prepare the project that will be used to deploy your application
+
.Create project
[source,shell,subs="attributes+"]
----
{command_line_tool} create project {default_namespace}
----
--

. Set the Kubernetes context to the newly created namespace using the following command:
+
--
.Set OpenShift current project
[source,shell]
----
{command_line_tool} project {default_namespace}
----

[TIP]
====
You can use the link:build-workflow-image-with-quarkus-cli.html#proc-building-serverless-workflow-application-using-native-image[native image] for a faster startup.
====


=== Preparing the OpenShift's Registry
OpenShift comes with a registry where you can push your images built locally to be deployed.

First, let's check if the Registry is already exposed, to do that, check if the route is exposed:

.Check whether the OpenShift registry is exposed
[source,shell]
----
oc get route default-route -n openshift-image-registry --template='{{ .spec.host }}'
----

If no information is returned here, it does mean that it is not exposed, to expose the registry follow link:{ocp_expose_registry_url}[these] steps.

Now that we have the OpenShift registry exposed, let's store into the `OPENSHIFT_REGISTRY_URL` environment variable, so we can use it easily in the next steps:

.Retrieve the OpenShift registry
[source,shell]
----
OPENSHIFT_REGISTRY_URL=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }})'
----
.Retrieve the OpenShift registry
[source,shell]
----
OPENSHIFT_REGISTRY_URL=$(oc get route default-route -n openshift-image-registry --template='{{ .spec.host }})'
----

The OpenShift's registry requires you to be logged in to be allowed to push Container Images. If you are already logged in the cluster you can use your token to authenticate to the OpenShift's registry:

.Log in to the OpenShift's registry
[source,shell]
----
podman login -u <USERNAME> -p $(oc whoami -t) --tls-verify=false $OPENSHIFT_REGISTRY_URL
----
If everything is working, you should get the *Login Succeeded!* message.

The next step is to deploy your workflow application and execute it.
You can read further the next sections which explain different approaches to deploy your {product_name} application:

* <<proc-deploy-sw-application-knative-cli,Using Knative CLI (kn)>>
* <<proc-deploy-sw-application-openfhift-client,Using OpenShift command-line tool>>
* <<proc-deploy-sw-application-quarkus-cli,Using Quarkus CLI>>

// deploy with kn-cli
include::../common/_proc_deploy_sw_kn_cli.adoc[]

// deploy with kubectl
include::../common/_proc_deploy_sw_oc.adoc[]

// deploy with quarkus-cli
include::../common/_proc_deploy_sw_quarkus_cli.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]