= Workflow plugin for Knative CLI
06-30-2022
:compat-mode!:
// Metadata:
:description: Overview of the Workflow plugin for the Knative CLI
:keywords: kogito, workflow, serverless, knative, plugin

`kn-plugin-workflow` is a plugin of the Knative Client, to enable users to quickly set up a local Kogito Serverless Workflow project from the command line.


.Prerequisites
* {java_install_url}[Java] at least version {java_min_version}
* {maven_install_url}[Maven] at least version {maven_min_version}
* {docker_install_url}[Docker] (Optional)
* {podman_install_url}[Podman] (Optional)
* {kubectl_install_url}[Kubernetes CLI].

== Instalation

You can download the latest binaries from the {kie_tools_releases_url}[Releases] page.

There are two ways to run `kn workflow`:

. You can run it standalone, just put it on your system path and make sure it is executable.
. You can install it as a plugin of the `kn` client to run:
* Follow the {kn_cli_install_url}[documentation] to install `kn` CLI if you don't have it
* Copy the `kn-workflow` binary to a directory on your `PATH` (for example, `/usr/local/bin`) and make sure its filename is `kn-workflow`
* On macOS give the ownership to the root user:
`sudo chown root: /usr/local/bin/kn-workflow`
* Run `kn plugin list` to verify that the `kn-workflow` plugin is installed successfully

After the plugin is installed, you can use `kn workflow` to run its related subcommands.

== Usage

[source,shell]
----
Usage:
  kn workflow [command]

Available Commands:
  build       Build a Kogito Serverless Workflow project and generate a container image
  completion  Generate the autocompletion script for the specified shell
  create      Create a Kogito Serverless Workflow project
  deploy      Deploy a Kogito Serverless Workflow project
  help        Help about any command

Flags:
  -h, --help      help for kn-workflow
  -v, --verbose   Print verbose logs

Use "kn workflow [command] --help" for more information about a command.
----

=== create

This command will scaffold a new Kogito Serverless Workflow project named "my-project":

[source,shell]
----
kn workflow create --name my-project
----

=== build

Builds a Kogito Serverless Workflow project in the current directory and generate a specific image:

[source,shell]
----
kn workflow build --image quay.io/mysuer/myproject
----

=== deploy

Deploys a Kogito Serverless Workflow project in the current directory (build command is required):

[source,shell]
----
kn workflow deploy
----

== Building from Source

[source,shell]
----
git clone git@github.com:kie-group/kie-tools.git
cd kie-tools
yarn bootstrap
cd packages/kn-plugin-workflow
go mod tidy
yarn build
----

include::../../pages/_common-content/report-issue.adoc[]
