= Workflow plugin for Knative CLI
06-30-2022
:compat-mode!:
// Metadata:
:description: Overview of the Workflow plugin for the Knative CLI
:keywords: kogito, workflow, serverless, knative, plugin

`kn-plugin-workflow` is a plugin of the Knative Client, to enable users to quickly set up a local Kogito Serverless Workflow project from the command line.

.Prerequisites
* {java_install_url}[Java] at least version {java_min_version}
* {maven_install_url}[Maven] at least version {maven_min_version}
* {docker_install_url}[Docker] (Optional)
* {podman_install_url}[Podman] (Optional)
* {kubectl_install_url}[Kubernetes CLI].

== Instalation

You can download the latest binaries from the {kie_tools_releases_url}[Releases] page.

There are two ways to run `kn workflow`:

. You can run it standalone, just put it on your system path and make sure it is executable.
. You can install it as a plugin of the `kn` client to run:
* Follow the {kn_cli_install_url}[documentation] to install `kn` CLI if you don't have it
* Copy the `kn-workflow` binary to a directory on your `PATH` (for example, `/usr/local/bin`) and make sure its filename is `kn-workflow`
* On macOS give the ownership to the root user:
`sudo chown root: /usr/local/bin/kn-workflow`
* Run `kn plugin list` to verify that the `kn-workflow` plugin is installed successfully

After the plugin is installed, you can use `kn workflow` to run its related subcommands.

== Usage
After the installation, you will be able to use the `workflow` subcommand in the Knative CLI. It's possible to use in two ways:

[source,shell]
----
kn workflow
kn-workflow
----

Running the command above, the following help message will appear:
[source,text]
----
Manage Kogito Serverless Workflow projects

Usage:
  kn workflow [command]

Available Commands:
  build       Build a Kogito Serverless Workflow project and generate a container image
  completion  Generate the autocompletion script for the specified shell
  create      Create a Kogito Serverless Workflow project
  deploy      Deploy a Kogito Serverless Workflow project
  help        Help about any command

Flags:
  -h, --help      help for kn-workflow
  -v, --verbose   Print verbose logs

Use "kn workflow [command] --help" for more information about a command.
----

=== create
This command will scaffold a new Kogito Serverless Workflow project in the current directory.

It sets up a Quarkus project with minimal extensions to build a Kogito Serverless Workflow  project. Also, the generated project has a "hello world" workflow.sw.json located on the
./<project-name>/src/main/resources directory.

[source,shell]
----
kn workflow create
----

By default the generated project is named "new-project". This name can be overritten with the `[-n|--name]` flag.

[source,shell]
----
kn workflow create --name my-project
----
This example creates a new project called "my-project".

Also, it's possible to add more extensions to the Quarkus project during its creation, by using the `[-e|--extension]` flag. You can pass more than one extension, but they need to be separated by a comma.

[source,shell]
----
kn workflow create --extension quarkus-jsonp,quarkus-smallrye-openapi
----
This example creates a new project with two additional extensions, "quarkus-jsonp" and "quarkus-smallrye-openapi".

NOTE: Running the `create` command for the first time can take a while, due to the necessity to download all dependencies for the Quarkus project.

=== build
The build command, builds a Kogito Serverless Workflow project in the current directory and generate a container image.

NOTE: To use this command `--image` or `--image-name` flag need to be used.

[source,shell]
----
kn workflow build --image my-project
kn workflow build --image-name my-project
----
This example generate a local image named "quay.io/my-project:latest". Note that the `registry` and `tag` defaults are `quay.io` and `latest` respectivly.

==== Image naming options
Let's take a better look in the image naming options.

The `[-i|--image]` flag can be used in several ways.
* --image=[name]
* --image=[name]:[tag]
* --image=[repository]/[name]
* --image=[repository]/[name]:[tag]
* --image=[registry]/[repository]/[name]
* --image=[registry]/[repository]/[name]:[tag]

Also, it's possible to use the specific flags to compose the image full name. The flags are:
* --image-registry
* --image-repository
* --image-name
* --image-tag

NOTE: If the --image flag is provided together with any of these flags, the specifc value will override --image.

[source,shell]
----
kn workflow build --image my-user/my-project:1.0.0 --image-repository other-user --image-tag 1.0.1
----
The example above will result in an image named `quay.io/other-user/my-project:1.0.1`

==== Building strategy
We have two different strategies to build the project and generate the image.

. Jib
Jib is an extension that enables building a container image without the necessity of a container runtime. Rebuilds are fast and the resultant image is optimized.

The following commands builds the image using Jib and save it in the Docker or Podman runtime respectivaly.
[source,shell]
----
kn workflow build --image my-project --jib
kn workflow build --image my-project --jib-podman
----

If you don't want to use any container runtime, use the `--push` option, so the built image will be imediatly pushed to the respecitive registry.
[source,shell]
----
kn workflow build --image my-project --jib --push
----
NOTE: You need to be authenticated in your registry to this command work. Remember, the resultant image in this case is "quay.io/my-project:latest".

. Docker
Building with Docker is straight forward as it's the default option. Also, it's possible to automatically push the image to the respecitive registry by using the `--push` option.
[source,shell]
----
kn workflow build --image my-project --push
----

=== deploy

Deploys a Kogito Serverless Workflow project in the current directory (build command is required):

[source,shell]
----
kn workflow deploy
----

== Building from Source

[source,shell]
----
git clone git@github.com:kie-group/kie-tools.git
cd kie-tools
yarn bootstrap
cd packages/kn-plugin-workflow
go mod tidy
yarn build
----

include::../../pages/_common-content/report-issue.adoc[]
