= Developing Workflow Services with the Operator
:compat-mode!:
// Metadata:
:description: Developing workflow service with the operator on Kubernetes
:keywords: kogito, workflow, serverless, operator, kubernetes, minikube, devmode

This document describes how you can develop your workflows directly on Kubernetes with the {operator_name}.

Workflows in development profile are not tailored for production environments. To build and deploy an immutable workflow application with the operator, see xref:cloud/operator/build-and-deploy-applications.adoc[].

== Introduction to the Development Profile

The development profile is the easiest way of starting playing around with workflows and the operator. 

To get started, you can use the editor of your choice to create a new Kubernetes Workflow YAML definition. For example:

.Example of a Kubernetes {product_name} YAML definition
[source,yaml,subs="attributes+"]
----
apiVersion: sw.kogito.kie.org/v1alpha08
kind: KogitoServerlessWorkflow
metadata:
  name: greeting
  annotations:
    sw.kogito.kie.org/description: Greeting example on k8s!
    sw.kogito.kie.org/version: 0.0.1
    sw.kogito.kie.org/profile: dev <2>
spec: <1>
  start: ChooseOnLanguage
  functions:
    - name: greetFunction
      type: custom
      operation: sysout
  states:
    - name: ChooseOnLanguage
      type: switch
      dataConditions:
        - condition: "${ .language == \"English\" }"
          transition: GreetInEnglish
        - condition: "${ .language == \"Spanish\" }"
          transition: GreetInSpanish
      defaultCondition: GreetInEnglish
    - name: GreetInEnglish
      type: inject
      data:
        greeting: "Hello from JSON Workflow, "
      transition: GreetPerson
    - name: GreetInSpanish
      type: inject
      data:
        greeting: "Saludos desde JSON Workflow, "
      transition: GreetPerson
    - name: GreetPerson
      type: operation
      actions:
        - name: greetAction
          functionRef:
            refName: greetFunction
            arguments:
              message:  ".greeting+.name"
      end: true
----

<1> In the `spec` attribute goes the workflow definition as described by the xref:getting-started/cncf-serverless-workflow-specification-support.adoc[CNCF Serverless Workflow specification]. So if you already have a workflow definition, you can use it there. Alternatively, you can use the xref:tooling/serverless-workflow-editor/swf-editor-overview.adoc[editors to create your workflow definition].

<2> The annotation `sw.kogito.kie.org/profile: dev` tells to the operator to deploy your workflow using the devlopment profile. This means that the operator will build a running instance of the workflow ready to receive changes during your development cycle.

You can make changes to the definition using any Kubernetes editor such as `kubectl`. The operator ensures that the latest workflow definition is running and ready. This way, you can include the workflow application in your development scenario and start making requests to it.

== Deploying a New Workflow Service

.Prerequisites
* You have xref:cloud/operator/install-serverless-operator.adoc[installed the {operator_name}]
* You have created a new {product_name} Kubernetes YAML file

Having a new Kubernetes workflow definition in a YAML file, you can deploy it in your cluster with the following command:

.Deploying a new KogitoServerlessWorkflow custom resource in Kubernetes
[source,bash,subs="attributes+"]
----
kubectl apply -f <your_file> -n <your_namespace>
----

Alternatively, you can try one of the examples available in the operator repository:

.Deploying the greeting workflow example
[source,bash,subs="attributes+"]
----
kubectl apply -f https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/{operator_version}/config/samples/sw.kogito_v1alpha08_kogitoserverlessworkflow.yaml -n <your_namespace>
----

[TIP]
====
Replace `<your_namespace>` with the namespace you're using to deploy your applications
====

You can follow the workflow status to check if everything is fine with:

.Checking the workflow status
[source,bash,subs="attributes+"]
----
kubectl get workflow -w
----

You should see the workflow conditions evolving to `READY` in a few seconds:

.Example workflow deployment status
[source,bash,subs="attributes+"]
----
NAME       PROFILE   VERSION   ADDRESS   READY   REASON
greeting   dev       0.0.1               False   WaitingForDeployment
greeting   dev       0.0.1               True
----

[TIP]
====
The `REASON` field gives you a cue about the current workflow status.
====

From here, you can make any changes to the workflow definition in the YAML file and apply it again to the cluster. After doing that, in a few seconds the new version of your workflow should be ready to receive new requests.

== Troubleshooting the Workflow Service




== Additional resources

* xref:cloud/operator/known-issues.adoc[]
* xref:cloud/operator/build-and-deploy-applications.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]
