= Supporting Services
:compat-mode!:
// Metadata:
:description: Deploy Supporting Services with {operator_name}
:keywords: kogito, sonataflow, workflow, serverless, operator, kubernetes, openshift, containers, data, index, job, service, cluster, wide, scoped, cluster-wide, cluster-scoped
// links
:kogito_serverless_operator_url: https://github.com/apache/incubator-kie-kogito-serverless-operator/

Under the hood, {operator_name} supports several services that enhance its capabilities. For example 
xref:data-index/data-index-core-concepts.adoc[Data Index] or xref:job-services/core-concepts.adoc[Job service].
Please take a look at these guides to learn more about them.

By default, workflows deployed by the operator use an embedded version of xref:data-index/data-index-core-concepts.adoc[Data Index], however non-embedded options are supported as well. This document describes how to deploy and configure supporting services, like Data Index or Job Service, on a cluster using the link:{kogito_serverless_operator_url}[{operator_name}].

[IMPORTANT]
====
{operator_name} is under active development with features yet to be implemented. Please see xref:cloud/operator/known-issues.adoc[].
====

.Prerequisites
* The {operator_name} installed. See xref:cloud/operator/install-serverless-operator.adoc[] guide
* A postgresql database. Required if you are planning to use non-embedded postgresql versions of supporting services. We recommend creating a postgresql deployment in your cluster. Please note your credentials.

[#deploy-supporting-services]
== Deploy supporting services

[#deploy-data-index-service]
=== Data Index

You can deploy Data Index via `SonataFlowPlatform` configuration. The operator will then configure all new workflows, with the "preview" or "gitops" profile, to use that Data Index.

Following is a basic configuration. It will deploy an ephemeral Data Index to the same namespace as the `SonataFlowPlatform`.

.Example of a SonataFlowPlatform instance with an ephemeral Data Index deployment
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    dataIndex: {}
----

If your use case requires persistence, Data Index supports a `postgresql` database.
First, you need to create a secret with credentials to access your postgresql deployment.

.Create a Secret for datasource authentication.
[source,bash,subs="attributes+"]
----
kubectl create secret generic <creds-secret> --from-literal=POSTGRESQL_USER=<user> --from-literal=POSTGRESQL_PASSWORD=<password> --from-literal=POSTGRESQL_DATABASE=<db_name> -n workflows
----

.Example of a SonataFlowPlatform instance with a Data Index deployment persisted to a postgresql database
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    dataIndex:
      persistence:
        postgresql:
          secretRef:
            name: <creds-secret> <1>
          serviceRef:
            name: <postgresql-service> <2>
----

<1> Name of your postgresql credentials secret
<2> Name of your postgresql k8s service

.Example of a SonataFlowPlatform instance with a persisted Data Index deployment and custom pod configuration
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    dataIndex:
      enabled: false <1>
      persistence:
        postgresql:
          secretRef:
            name: <creds-secret>
            userKey: <secret-user-key> <2>
          jdbcUrl: "jdbc:postgresql://host:port/database?currentSchema=data-index-service" <3>
      podTemplate:
        replicas: 1 <4>
        container:
          image: <image:tag> <5>
----

<1> Determines whether "preview"  or "gitops" profile workflows should be configured to use this service, defaults to `true`
<2> Secret key of your postgresql credentials user, defaults to `POSTGRESQL_USER`
<3> PostgreSql JDBC URL
<4> Number of Data Index pods, defaults to `1`
<5> Custom Data Index container image name, if customization is required


[#deploy-job-service]
=== Job Service

You can deploy Job Service via `SonataFlowPlatform` configuration. The operator will then configure all new workflows, with the "preview" profile, to use that Job Service.

Following is a basic configuration. It will deploy an ephemeral Job Service to the same namespace as the `SonataFlowPlatform`.

.Example of a SonataFlowPlatform instance with an ephemeral Job Service deployment
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    jobService: {}
----

If your use case requires persistence, Job Service supports a `postgresql` database.
First, you need to create a secret with credentials to access your postgresql deployment.

.Create a Secret for datasource authentication.
[source,bash,subs="attributes+"]
----
kubectl create secret generic <creds-secret> --from-literal=POSTGRESQL_USER=<user> --from-literal=POSTGRESQL_PASSWORD=<password> --from-literal=POSTGRESQL_DATABASE=<db_name> -n workflows
----

.Example of a SonataFlowPlatform instance with a Job Service deployment persisted to a postgresql database
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    jobService:
      persistence:
        postgresql:
          secretRef:
            name: <creds-secret> <1>
          serviceRef:
            name: <postgresql-service> <2>
----

<1> Name of your postgresql credentials secret
<2> Name of your postgresql k8s service

.Example of a SonataFlowPlatform instance with a persisted Job Service deployment and custom pod configuration
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  services:
    jobService:
      enabled: false <1>
      persistence:
        postgresql:
          secretRef:
            name: <creds-secret>
            userKey: <secret-user-key> <2>
          jdbcUrl: "jdbc:postgresql://host:port/database?currentSchema=data-index-service" <3>
      podTemplate:
        replicas: 1 <4>
        container:
          image: <image:tag> <5>
----

<1> Determines whether "preview" or "gitops" profile workflows should be configured to use this service, defaults to `true`
<2> Secret key of your postgresql credentials user, defaults to `POSTGRESQL_USER`
<3> PostgreSql JDBC URL
<4> Number of Job Service pods, defaults to `1`
<5> Custom Job Service container image name, if customization is required

[#cluster-wide-services]
== Cluster-Wide Supporting Services

The `SonataFlowClusterPlatform` CR is optionally used to specify a cluster-wide set of supporting services for workflow consumption. This is done by referencing an existing, namespaced `SonataFlowPlatform` resource.

Following is a basic configuration that allows workflows, deployed in any namespace, to leverage supporting services configured in the chosen "central" namespace.

.Example of a basic SonataFlowClusterPlatform CR
[source,yaml,subs="attributes+"]
----
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: <central namespace>
----

[NOTE]
====
These cluster-wide services can be overridden in any namespace, by configuring that namespace's `SonataFlowPlatform.spec.services`.
====

== Additional resources

* xref:data-index/data-index-service.adoc[]
* xref:cloud/operator/enabling-jobs-service.adoc[]
* xref:cloud/operator/known-issues.adoc[]

include::../../../pages/_common-content/report-issue.adoc[]
