= {page-component-title}

{product_name} is a tool for building cloud-native workflow applications. You can use it to do the services and events orchestration and choreography. Currently, with {product_name} you can integrate with services and events in your architecture using:

1. **CloudEvents**. Ideal for an Event-Driven architecture where the services are ready to consume and produce events working in a more reactive way.
2. **Sync or Async REST services invocations via OpenAPI/Async API**. There are options even to directly call a REST service in the architecture or ecosystem. Either async or sync methods are supported depending on your requirements.
3. **Internal Service execution or invocation**. {product_name} is also a workflow framework to build applications. You can use it to create custom services in the same thread to run a lightweight workflow-based application within the same instance.

You can learn how to create, manage, and deploy your workflow applications with the following guides.

[.card-section]
== Getting started

[.card]
--
[.card-title]
xref:getting-started/create-your-first-workflow-service.adoc[]
[.card-description]
Learn how to create your first Quarkus Workflow Project
--

[.card]
--
[.card-title]
xref:getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc[]
[.card-description]
Learn how to create & run your first {Kogito Serverless Workflow} project.
--

// We will refactor this section here: https://issues.redhat.com/browse/KOGITO-9451
//[.card]
//--
//[.card-title]
//xref:getting-started/getting-familiar-with-our-tooling.adoc[Getting familiar with {product_name} tooling]
//[.card-description]
//Learn which tools you can use to author your workflow assets
//--

[.card-section]
== Core Concepts

[.card]
--
[.card-title]
xref:core/cncf-serverless-workflow-specification-support.adoc[]
[.card-description]
Learn about the CNCF Serverless Workflow Specification implementation
--

[.card]
--
[.card-title]
xref:core/handling-events-on-workflows.adoc[]
[.card-description]
Learn how to use the Event state in your workflow application
--

[.card]
--
[.card-title]
xref:core/working-with-callbacks.adoc[]
[.card-description]
Learn how to use the Callback state in your workflow application
--

[.card]
--
[.card-title]
xref:core/understanding-jq-expressions.adoc[]
[.card-description]
Learn how to create jq expressions to manipulate data within a workflow execution
--

[.card]
--
[.card-title]
xref:core/understanding-workflow-error-handling.adoc[]
[.card-description]
Learn how to handle errors in your workflow application
--

[.card]
--
[.card-title]
xref:core/configuration-properties.adoc[]
[.card-description]
Quick reference of configuration properties in workflow
--

[.card]
--
[.card-title]
xref:core/defining-an-input-schema-for-workflows.adoc[]
[.card-description]
Learn about the input schema definition used to validate the workflow data input against a defined JSON Schema
--

[.card]
--
[.card-title]
xref:core/custom-functions-support.adoc[]
[.card-description]
Learn about the custom functions supported by Serverless Workflow
--

[.card]
--
[.card-title]
xref:core/timeouts-support.adoc[]
[.card-description]
Learn how to configure timeouts in the workflow
--

[.card]
--
[.card-title]
xref:core/working-with-parallelism.adoc[]
[.card-description]
Working with parallelism in your workflow project
--

[.card-section]
== Tooling

[.card]
--
[.card-title]
xref:tooling/serverless-workflow-editor/swf-editor-overview.adoc[Serverless Workflow editor]
[.card-description]
Learn how to install and use the Serverless Workflow editor
--

[.card]
--
[.card-title]
xref:tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc[VS Code extension for Serverless Workflow editor]
[.card-description]
Learn how to install and use the VS Code extension for Serverless Workflow editor for creating workflows.
--

[.card]
--
[.card-title]
xref:tooling/serverless-logic-web-tools/serverless-logic-web-tools-overview.adoc[{serverless_logic_web_tools_name}]
[.card-description]
Learn how to use {serverless_logic_web_tools_name} for creating and managing workflows, decisions, and dashboards.
--

[.card]
--
[.card-title]
xref:tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc[Chrome extension for Serverless Workflow editor on GitHub]
[.card-description]
Learn how to install and use the Chrome extension for Serverless Workflow editor to view and edit workflows directly in Github.
--

[.card-section]
== Service Orchestration

[.card]
--
[.card-title]
xref:service-orchestration/orchestration-of-openapi-based-services.adoc[]
[.card-description]
Learn how to orchestrate REST services using OpenAPI specification descriptors
--

[.card]
--
[.card-title]
xref:service-orchestration/working-with-openapi-callbacks.adoc[]
[.card-description]
Learn how to use the OpenAPI Callback in your workflow application
--

[.card]
--
[.card-title]
xref:service-orchestration/orchestration-of-grpc-services.adoc[]
[.card-description]
Learn about orchestrating gRPC services
--

[.card-section]
== Event Orchestration

[.card]
--
[.card-title]
xref:eventing/orchestration-of-asyncapi-based-services.adoc[]
[.card-description]
Learn how to trigger and consume events using AsyncAPI specification descriptors
--

[.card]
--
[.card-title]
xref:eventing/event-correlation-with-workflows.adoc[]
[.card-description]
Learn how to configure event correlation in your workflow application
--

[.card]
--
[.card-title]
xref:eventing/consume-producing-events-with-kafka.adoc[]
[.card-description]
Learn how to configure your Quarkus Workflow Project to produce and consume events using Apache Kafka
--

[.card]
--
[.card-title]
xref:eventing/consume-produce-events-with-knative-eventing.adoc[]
[.card-description]
Learn how to configure your Quarkus Workflow Project to produce and consume events on Knative Eventing
--

[.card-section]
== Security

[.card]
--
[.card-title]
xref:security/authention-support-for-openapi-services.adoc[]
[.card-description]
Learn how to use authentication methods when calling REST services using OpenAPI specification
--

[.card]
--
[.card-title]
xref:security/orchestrating-third-party-services-with-oauth2.adoc[]
[.card-description]
Learn about the OAuth2 method support when orchestrating REST services using your workflow application
--

[.card-section]
== Executing, Testing and Troubleshooting

[.card]
--
[.card-title]
xref:testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc[Kogito Serverless Workflow Tools extension in Quarkus Dev UI]
[.card-description]
Learn how to use the Serverless Workflow extension in Quarkus Dev UI
--

[.card]
--
[.card-title]
xref:testing-and-troubleshooting/kn-plugin-workflow-overview.adoc[{product_name} plug-in for Knative CLI]
[.card-description]
Learn how to install the {product_name} plug-in for Knative CLI
--

[.card]
--
[.card-title]
xref:testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc[]
[.card-description]
Testing Quarkus Workflow Project that uses HTTP CloudEvents and Knative Sink Binding
--

[.card]
--
[.card-title]
xref:testing-and-troubleshooting/mocking-openapi-services-with-wiremock.adoc[]
[.card-description]
Learn how to mock external REST requests when testing your Quarkus Workflow Project
--

[.card]
--
[.card-title]
xref:testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc[]
[.card-description]
Learn how to add unit tests in your Quarkus Workflow Project using RestAssured
--

[.card-section]
== Persistence

[.card]
--
[.card-title]
xref:persistence/persistence-with-postgresql.adoc[]
[.card-description]
Running Quarkus Workflow Applications using PostgresSQL
--

[.card]
--
[.card-title]
xref:persistence/postgresql-flyway-migration.adoc[]
[.card-description]
Migrating your existing PostgreSQL Database with changes from the {product_name} upgrade using Flyway
--

[.card]
--
[.card-title]
xref:persistence/integration-tests-with-postgresql.adoc[]
[.card-description]
Learn how to integrate tests on Quarkus Workflow Applications that use PostgreSQL as a persistence storage
--

[.card-section]
== Cloud

[.card]
--
[.card-title]
xref:cloud/index.adoc[{product_name} in the Cloud]
[.card-description]
Learn about the options to deploy workflow applications in Kubernetes
--

[.card-section]
== Integrations

[.card]
--
[.card-title]
xref:integrations/camel-routes-integration.adoc[]
[.card-description]
Learn how to use Camel Routes within your workflow application
--

[.card]
--
[.card-title]
xref:integrations/custom-functions-knative.adoc[]
[.card-description]
Learn how to invoke Knative Services from {product_name} custom functions
--

[.card]
--
[.card-title]
xref:integrations/expose-metrics-to-prometheus.adoc[]
[.card-description]
Exposing the workflow base metrics to Prometheus
--

[.card]
--
[.card-title]
xref:integrations/serverless-dashboard-with-runtime-data.adoc[]
[.card-description]
Learn how to use dashboards to display the runtime data of your workflow application
--

[.card-section]
== Job Service

[.card]
--
[.card-title]
xref:job-services/core-concepts.adoc[]
[.card-description]
Details about Job Service to control timers in {PRODUCT_NAME}
--

[.card]
--
[.card-title]
xref:job-services/quarkus-extensions.adoc[]
[.card-description]
Details about how to configure you Quarkus Workflow Project to interact with the Job Service in {PRODUCT_NAME}
--

[.card-section]
== Data Index service

[.card]
--
[.card-title]
xref:data-index/data-index-core-concepts.adoc[]
[.card-description]
Learn Data Index core concepts, allowing to understand the purpose and the different deployment options that are provided.
--

[.card]
--
[.card-title]
xref:data-index/data-index-service.adoc[]
[.card-description]
Go deeper in details about Data Index as standalone service deployment.
--

[.card]
--
[.card-title]
xref:data-index/data-index-quarkus-extension.adoc[]
[.card-description]
Explore Data Index as Quarkus extensions in  {PRODUCT_NAME}
--

[.card]
--
[.card-title]
xref:data-index/data-index-usecase-singleton.adoc[Operator Data Index Deployment]
[.card-description]
Learn about the options to deploy workflow applications and Data Index using The {PRODUCT_NAME} Operator
--

[.card-section]
== Use Cases

[.card]
--
[.card-title]
xref:use-cases/orchestration-based-saga-pattern.adoc[]
[.card-description]
Learn how and when to use the SAGA pattern in your workflow projects
--

[.card]
--
[.card-title]
xref:use-cases/timeout-showcase-example.adoc[]
[.card-description]
Learn how and when to use timeout in your workflow projects
--