// links
:quarkus_k8s_deploy_url: https://github.com/quarkusio/quarkus/issues/26385

[[proc-deploy-sw-application-quarkus-cli]]
=== Deploying your workflow application using Quarkus CLI

.Prerequisites
* Workflow application is installed.
* Quarkus CLI is installed. +
For more information, see link:{quarkus_cli_url}[Building Quarkus Apps with Quarkus command line interface (CLI)].
* You have completed the steps in link:#proc-deploy-sw-application-kubectl[Deploying your workflow application using `kubectl`]

.Procedure
. Add the Quarkus extensions to deploy the `knative` service
+
--
You can add the Kubernetes and the Kogito Knative extensions to your project with the Quarkus CLI:

.Add kubernetes and Kogito knative extensions to the project with Quarkus CLI
[source,shell]
----
quarkus extension add kubernetes
quarkus extension add kogito-addons-quarkus-knative-eventing
----
--
. To deploy your workflow application using Quarkus CLI, set the following system properties in `application.properties` file:
+
--
.Required system properties
[source,properties]
----
quarkus.knative.name=greeting-quarkus-cli <1>
quarkus.kubernetes.deployment-target=knative <2>
quarkus.kubernetes.deploy=true <3>
quarkus.container-image.push=false <4>
----

<1> Property for the Knative resource name
<2> Property to set whether or not deploy on an active Kubernetes cluster
<3> {container_push}

[IMPORTANT]
====
This feature works with Quarkus 2.10.2.Final or later. For more information, see
link:{quarkus_k8s_deploy_url}[link].
====
--

. Verify if your workflow application is deployed correctly:
+
--
[tabs]
====
On kubectl::
+
[source,shell]
----
kubectl get services.serving.knative.dev greeting-quarkus-cli
----
On Knative CLI::
+
[source,shell]
----
kn service list greeting-quarkus-cli
----
====

.Example output
[source,shell]
----
NAME                   URL                                                                                      LATEST                       AGE    CONDITIONS   READY   REASON
greeting-quarkus-cli   http://greeting-quarkus-cli.serverless-workflow-greeting-quarkus.10.103.94.37.sslip.io   greeting-quarkus-cli-00001   7m6s   3 OK / 3     True
----
--

. You can access your workflow application using the listed URL in the output.
+
--
.Access your workflow application
[source,shell]
----
curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' -d '{"name": "John", "language": "English"}' http://greeting-quarkus-cli.serverless-workflow-greeting-quarkus.10.103.94.37.sslip.io/jsongreet.37.sslip.io/jsongreet
----
--