= Invoking Knative services from {context} custom functions
:compat-mode!:
// Metadata:
:description: Explain what is and how the Knative service discovery works
:keywords: kogito, workflow, quarkus, serverless, service-discovery, knative

This document describes how to call Knative services using {context} custom functions. The procedure described in this document is based on the link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative[`serverless-workflow-custom-function-knative`] example application.

The testing procedure in this document is based on the serverless-workflow-examples/serverless-workflow-custom-function-knative example application. You can access this example application in the link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative[Kogito Examples] GitHub repository.

.Prerequisites

include::common/_prerequisites.adoc[]

[[about-custom-functions-for-knative]]
== About {context} custom functions for Knative

{product_name} provides an implementation of xref:core/custom-functions-support.adoc[{context} custom function] through the `knative-serving` add-on to invoke Knative services. It allows you to have a static URI, defining a Knative service, which is used to perform HTTP requests. The Knative service defined in the URI is queried in the current Knative cluster and translated to a valid URL.

For instance, given the following deployed Knative service:

[source,bash]
----
$ kn service list
NAME                              URL                                                                      LATEST                                  AGE     CONDITIONS   READY   REASON
custom-function-knative-service   http://custom-function-knative-service.default.10.109.169.193.sslip.io   custom-function-knative-service-00001   3h16m   3 OK / 3     True
----

You can declare a {context} custom function using the Knative service name, like the following:

[source,json]
----
  "functions": [
    {
      "name": "greet",
      "type": "custom",
      "operation": "knative:custom-function-knative-service"
    }
  ]
----

The above function will send a `POST` request to the http://custom-function-knative-service.default.10.109.169.193.sslip.io URL.

[NOTE]
====
`GET` requests are not yet supported.
====

[[about-namespaces]]
=== About namespaces

Note that in the above example you declared only the name of the service you wanted to call, but not a namespace. In this case, {product_name} will look for a Knative service in the same namespace the workflow service is running.

In case you need to call a Knative service in a different namespace, you can declare the function as:

[source,json]
----
  "functions": [
    {
      "name": "greet",
      "type": "custom",
      "operation": "knative:my_different_namespace/custom-function-knative-service"
    }
  ]
----

In the above example, {product_name} will look for the `custom-function-knative-service` in the `my_different_namespace` namespace.

=== About HTTP resource paths

You can specify the HTTP resource path by adding the `path` property to the function's metadata.

For instance, given the `/path/to/my/resource` HTTP resource path, you can define your function as:

[source,json]
----
  "functions": [
    {
      "name": "greet",
      "type": "custom",
      "operation": "knative:custom-function-knative-service",
      "metadata": {
        "path": "/path/to/my/resource"
      }
    }
  ]
----

In case you don't specify any path, the root path will be used. For instance, the following function:

[source,json]
----
  "functions": [
    {
      "name": "greet",
      "type": "custom",
      "operation": "knative:custom-function-knative-service"
    }
  ]
----

Is exactly the same as:

[source,json]
----
  "functions": [
    {
      "name": "greet",
      "type": "custom",
      "operation": "knative:custom-function-knative-service",
      "metadata": {
        "path": "/"
      }
    }
  ]
----

=== About the request payload

In case you need to send a payload in the request, you can add it to `arguments` in `functionRef`.

For instance, given you want to send the following JSON object as the payload:

[source,json]
----
{
  "product_id": ".product_id",
  "customer_name": ".customer_name"
}
----

You must declare a `functionRef` like the following.

[source,json]
----
  "states": [
    {
      "name": "invokeFunction",
      "type": "operation",
      "actions": [
        {
          "functionRef": {
            "refName": "greet",
            "arguments": { <1>
              "product_id": ".product_id",
              "customer_name": ".customer_name"
            }
          }
        }
      ],
      "end": true
    }
  ]
----
<1> The request payload is set in `arguments`.

=== About the request timeout

By default, the Knative service must respond within 10 seconds. You can use the `kogito.addon.knative-serving.request-timeout` property to configure this value.

For instance, if you want to reduce the request timeout to 5 seconds, you must add the following to your `application.properties` file:

[source,properties]
----
kogito.addon.knative-serving.request-timeout=5000 <1>
----
<1> Time in milliseconds

== Example

.Prerequisites

include::common/_prerequisites.adoc[]

* You have the link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative/custom-function-knative-service[custom-function-knative-service] project deployed on Knative. For more information on how to deploy a Quarkus project to Knative, see the https://quarkus.io/guides/deploying-to-kubernetes[Quarkus Kubernetes extension documentation].

.Procedure

. Add the `knative-serving` add-on dependency to your link:{kogito_sw_examples_url}/serverless-workflow-custom-function-knative/workflow[workflow] project.
+
--

[source,xml]
----
<dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-addons-quarkus-knative-serving</artifactId>
</dependency>
----

--

. Discover the name of the Knative service that your workflow will invoke. In a terminal window, run the following command:
+
--

[source,bash]
----
kn service list
----

You should see an output like:

[source,bash]
----
NAME                              URL                                                                      LATEST                                  AGE     CONDITIONS   READY   REASON
custom-function-knative-service   http://custom-function-knative-service.default.10.109.169.193.sslip.io   custom-function-knative-service-00001   3h16m   3 OK / 3     True
----

Save the Knative service name (`custom-function-knative-service`) to use it in the next step.

--

. Declare the Knative {context} custom function. In the `functions` section of your workflow, add the following:

+
--

[source,json]
----
{
  "name": "greet", <1>
  "type": "custom", <2>
  "operation": "knative:custom-function-knative-service", <3>
  "metadata": {
    "path": "/function" <4>
  }
}
----

<1> The name of the {context} function
<2> Indicates that this function is a custom one
<3> Indicates that your custom function is of type `knative` and it will invoke the `custom-function-knative-service` service.
<4> The resource path you want to access

--

. Invoke the declared function. In an `operation` state, add an `action` that references the function you declared in the previous step like the following:

+
--

[source,json]
----
"actions": [
  {
    "functionRef": {
      "refName": "greet", <1>
      "arguments": { <2>
        "name": ".name"
      }
    }
  }
]
----
<1> Function's name
<2> The payload that should be sent in the request

--

. Deploy your workflow service to Knative. For more information on how to deploy a {product_name} {context} project to Knative, see the xref:cloud/deploying-on-kubernetes.adoc[Deploying on Kubernetes].

. Submit a request to the workflow service

+
--
[source,bash]
----
curl -X 'POST' \
  '<URL>/knativeFunction' \ <1>
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{ "name": "Kogito" }'
----

<1> Replace `<URL>` with the URL of your deployed workflow service

You should see an output like (`id` will change):

[source,json]
----
{"id":"87cf8275-782d-4e0b-a9be-a95f95c9c190","workflowdata":{"name":"Kogito","greeting":"Greetings from Serverless Workflow, Kogito"}}
----

--

== Additional resources

* xref:cloud/deploying-on-minikube.adoc[Deploying your Serverless Workflow application on Minikube]
* xref:cloud/deploying-on-kubernetes.adoc[Deploying your Serverless Workflow application on Kubernetes]

include::../../pages/_common-content/report-issue.adoc[]