= Defining an input schema for {context}
:compat-mode!:
// Metadata:
:description: Defining input schema for Serverless Workflow
:keywords: kogito, workflow, serverless, dataInputSchema

The dataInputSchema in the link:{spec_doc_url}#workflow-definition-structure[Serverless Workflow specification] is one of the parameters in the Workflow definition.

The dataInputSchema parameter is used to validate the workflow data input against a defined JSON Schema. It is important to provide a dataInputSchema, as it can be used to check if the provided workflow data input is a right one before any states are executed.

The dataInputSchema can be defined as follows:
[source,json]
----
"dataInputSchema": {
   "schema": "URL_to_json_schema",
   "failOnValidationErrors": false
}
----

"schema" property is an URI, which holds the path to the JSON schema used to validate the workflow data input. The URI can be a classpath URI, a file or a http.If a classpath URI is specified, the JSON schema file should be placed in the resources section of the project.

An example for a workflow definition with datainputschema can be found here- link:{kogito_sw_examples_url}/serverless-workflow-expression-quarkus/src/main/resources/expression.sw.json[`serverless-workflow-expression-quarkus`]

You can find a sample JSON schema here- link:{kogito_sw_examples_url}/src/main/resources/schema/expression.json[`serverless-workflow-expression-quarkus-json`]

When a workflow definition has a dataInputSchema attribute defined, the application should generate an OpenAPI file (http://localhost/q/swagger-ui) referencing this schema file, which helps to correctly define the input data for the workflows.

This documents describes about link:{open_api_spec_url}[OpenAPI] specification file.

To generate an OpenAPI file for a Kogito Serverless workflow, the link:{quarkus_swagger_url}#expose-openapi-specifications[Quarkus dependency] must be added in the project.

.Example component section with schema in an OpenAPI file
[source,yaml]
----
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
----
[source,yaml]
