= Working with parallelism

// Metadata:
:description: Working with parallelism in Serverless Workflow
:keywords: kogito, workflow, quarkus, serverless, parallelism

This document describes how to run parallel tasks in Serverless Workflow.
The testing procedure in this document is based on the `serverless-workflow-examples/serverless-workflow-service-calls-quarkus` example application.
You can access this example application in the link:{kogito_sw_examples_url}/serverless-workflow-parallel-execution[GitHub repository].

[WARNING]
====
Kogito Serverless Workflow serialize parallel execution. Therefore, "parallel" does not mean simultaneous execution. It means there is no logical dependency between branches. An inactive branch can start/resume execution without waiting completion of the active branch if the latter suspends execution (for example, wait for an event reception).
====

The example application is a workflow that concatenates 3 strings and returns the result.
The concatenation is done in parallel, one branch per each of the 3 strings.

[[proc-creating-the-workflow]]
== Creating the workflow

The procedure in this section describes how you can create the workflow that is going to perform the concatenation.

.Prerequisites

include::../../pages/_common-content/getting-started-requirement.adoc[]

.Procedure
. Create a serverless workflow file under the `src/main/resources/` directory with the name `parallel.sw.json`.

. Add the following content to the file:
+
--
[source,json]
----
{
  "id": "parallel",
  "version": "1.0",
  "specVersion": "0.8",
  "name": "Welcome to the Parallel dimension",
  "description": "Testing parallelism",
  "start": "Parallel",
  "functions": [
    {
      "name": "concatA",
      "type": "expression",
      "operation": ".result|=.+\"A\"" <1>
    },
    {
      "name": "concatB",
      "type": "expression",
      "operation": ".result|=.+\"B\"" <2>
    },
    {
      "name": "concatC",
      "type": "expression",
      "operation": ".result|=.+\"C\"" <3>
    }
  ],
  "states": [
    {
      "name": "Parallel",
      "type": "parallel", <4>
      "branches": [ <5>
        {
          "name": "branchA",
          "actions": [
            {
              "functionRef": "concatA" <6>
            }
          ]
        },
        {
          "name": "branchB",
          "actions": [
            {
              "functionRef": "concatB" <7>
            }
          ]
        },
        {
          "name": "branchC",
          "actions": [
            {
              "functionRef": "concatC" <8>
            }
          ]
        }
      ],
      "completionType": "allOf", <9>
      "end": {
        "terminate": true
      }
    }
  ]
}
----

<1> Function that concatenates the string `A`
<2> Function that concatenates the string `B`
<3> Function that concatenates the string `C`
<4> Defines the type of the state as `parallel`
<5> Defines the branches that is going to run in parallel
<6> Defines the function that is going to run in the branch `branchA`
<7> Defines the function that is going to run in the branch `branchB`
<8> Defines the function that is going to run in the branch `branchC`
<9> Defines the completion type of the parallel state as `allOf`.
This means that the parallel state will be completed when all the branches are completed.

--

== Running the workflow

The procedure in this section describes how you can run the workflow.

.Prerequisites

* You have created the parallel workflow as described in <<proc-creating-the-workflow>>

* The workflow application is up and running.
You can start it in dev mode by running:
+
--
[source,shell]
----
`mvn quarkus:dev`
----
--

.Procedure
. Run the workflow by sending a request to the `/parallel` endpoint.
+
--
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8080/parallel' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "workflowdata": {}
}'
----

You should see an output similar to:
[source,json]
----
{"id":"358f97ba-f0f9-4f25-86cc-4b35e85c2406","workflowdata":{"result":"ABC"}}
----

[NOTE]
====
`"result":"ABC"` may be different in each request, since the branches are running in parallel and the execution order of the branches is unpredictable.
====

Note that the workflow data shows the concatenated string as result.
--

== Running only some branches

Rather than defining `"completionType": "allOf"` to run all branches, like in the previous example, you can define `"completionType": "atLeast"` to run only some branches if needed.

When you do that, you also need to define the minimum number of branches that you want to run, by defining the `"numCompleted":` property.

The procedure in this section describes how you can run the workflow with only two branches.

.Prerequisites

* You have created the parallel workflow as described in <<proc-creating-the-workflow>>

.Procedure
. Change the `completionType` property to `"atLeast"` and add the `"numCompleted": 2` property to the parallel state. Your workflow should look like:

+
--
[source,json]
----
{
  "id": "parallel",
  "version": "1.0",
  "specVersion": "0.8",
  "name": "Welcome to the Parallel dimension",
  "description": "Testing parallelism",
  "start": "Parallel",
  "functions": [
    {
      "name": "concatA",
      "type": "expression",
      "operation": ".result|=.+\"A\""
    },
    {
      "name": "concatB",
      "type": "expression",
      "operation": ".result|=.+\"B\""
    },
    {
      "name": "concatC",
      "type": "expression",
      "operation": ".result|=.+\"C\""
    }
  ],
  "states": [
    {
      "name": "Parallel",
      "type": "parallel",
      "branches": [
        {
          "name": "branchA",
          "actions": [
            {
              "functionRef": "concatA"
            }
          ]
        },
        {
          "name": "branchB",
          "actions": [
            {
              "functionRef": "concatB"
            }
          ]
        },
        {
          "name": "branchC",
          "actions": [
            {
              "functionRef": "concatC"
            }
          ]
        }
      ],
      "completionType": "atLeast", <1>
      "numCompleted": "2", <2>
      "end": {
        "terminate": true
      }
    }
  ]
}
----
<1> Defines the completion type of the parallel state as `atLeast`
<2> Defines the minimum number of branches that you want to run. This means that the parallel state will be completed when at least two branches are completed.
--

. Run the workflow by sending a request to the `/parallel` endpoint.

+
--
[source,shell]
----
curl -X 'POST' \
  'http://localhost:8080/parallel' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "workflowdata": {}
}'
----

You should see an output similar to:
[source,shell]
----
{"id":"3da62df1-c4e7-48c9-a3e4-7f63872c92f4","workflowdata":{"result":"BC"}}
----

[NOTE]
====
`"result":"BC"` may be different in each request.
====

Note that the workflow data shows the concatenated string as result, but now the workflow concatenated only 2 letters.
--

include::../../pages/_common-content/report-issue.adoc[]