:_content-type: PROCEDURE
:description: Bootstrapping a project
:keywords: bootstrap, project, serverless, workflow
:navtitle: Bootstrapping a project
// :page-aliases:

[id="proc-boostrapping-the-project_{context}"]
= Bootstrapping a project

To create your workflow service, first you need to bootstrap a project.

.Procedure
. In a command terminal, use one of the following commands to create a project:
+
[tabs]
====
Quarkus CLI::
+
--
.Create a project using Quarkus CLI
[source,shell,subs="attributes+"]
----
quarkus create app \
    -x={kogito_sw_ga} \
    -x=quarkus-container-image-jib \
    -x=quarkus-resteasy-jackson \
    -x=quarkus-smallrye-openapi \
    --no-code \
    org.kie.kogito.examples:serverless-workflow-hello-world:1.0
----
The previous command creates a Maven Quarkus project in the `serverless-workflow-hello-world` directory containing the required dependencies, including:
* `{kogito_sw_ga}`: Adds support for workflows.
* `quarkus-container-image-jib`: Adds support for Container Image Builds.
* `quarkus-resteasy-jackson`: Adds support for RESTEasy, which is required by the generated REST resources that are used to start the flow process using an HTTP request.
* `quarkus-smallrye-openapi`: Adds support for Swagger documentation when you run the application in development mode.
* `--no-code`: Prevents workflow example code from being generated.
The SwaggerUI is available at `http://localhost:8080/q/swagger-ui/` when you run the application.
--
Apache Maven::
+
--
.Create a project using Apache Maven
[source,shell,subs="attributes"]
----
mvn {quarkus_platform}:quarkus-maven-plugin:{quarkus_version}:create \
    -DprojectGroupId=org.kie.kogito.examples \
    -DprojectArtifactId=serverless-workflow-hello-world \
    -Dextensions="{kogito_sw_ga},quarkus-container-image-jib,quarkus-resteasy-jackson,quarkus-smallrye-openapi" \
    -DnoCode
cd serverless-workflow-hello-world
----
In the previous command, `org.kie.kogito.examples`, `serverless-workflow-hello-world`, and `1.0` is group ID, artifact ID, and version of your project respectively. `-DnoCode` prevents the generation of workflow example code.
--
Knative workflow CLI::
+
--
.Create a project using Knative workflow CLI
[source,shell,subs="attributes"]
----
kn workflow create \
  --name serverless-workflow-hello-world \
  --extension quarkus-jsonp,quarkus-smallrye-openapi \
  --quarkus-platform-group-id={quarkus_platform} \
  --quarkus-version={quarkus_version}
----
For more information about Knative workflow CLI, see xref:tooling/kn-plugin-workflow-overview.adoc[{context} plug-in for Knative CLI].
--
====
