= Data Index Quarkus Extension
:compat-mode!:
// Metadata:
:description: Data Index Service to allow to index and query audit data in {product_name}
:keywords: kogito, workflow, serverless, data, dataindex, data-index, index, service, extension, quarkus
// Referenced documentation pages
:persistence_with_postgresql_guide: xref:persistence/persistence-with-postgresql.adoc
:data-index-core-concepts_guide: xref:data-index/data-index-core-concepts.adoc
:getting_started_create_first_workflow_guide: xref:getting-started/create-your-first-workflow-service.adoc
// External pages
:kogito_sw_timeouts_showcase_embedded_example_url: {kogito_sw_examples_url}/serverless-workflow-timeouts-showcase-embedded
:kogito_sw_timeouts_showcase_embedded_example_application_properties_url: {kogito_sw_timeouts_showcase_embedded_example_url}/src/main/resources/application.properties
:infinispan_url: https://infinispan.org/
:mongo_url: https://www.mongodb.com/
:postgresql_url: https://www.postgresql.org/


This document describes how you add the Data Index features to your runtime service. You simply need to add the Data Index extension to the runtime and
all the audit data will be collected and stored in the database, and the graphQL endpoint will be available to execute queries and perform management operation over the workflows instances.

The example described in this document is based on the link:{kogito_sw_timeouts_showcase_embedded_example_url}[`serverless-workflow-timeouts_showcase_embedded`] example application.

[[data-index-ext-overview]]
== Overview

The Data Index service has been designed to store and manage audit data from different workflows that may be hosted in different runtimes.
Communication with the service is through events that contain the audit data and the service is responsible for storing them and exposing a GRAPHQL endpoint to allow queries and maintenance operations on the different instances of Workflows.

Sometimes, to avoid deploying the service separately, it could be interesting to have the audit storage functionality and the query possibility embedded in the same application.
For this purpose, we have the Quarkus Data Index extension that can be plugged to any workflow application and incorporates the Data Index functionality into the same application with no need of an external Data Index Service.
These extensions can be found distributed as Kogito addons: `kogito-addons-quarkus-data-index`.

[NOTE]
====
The Data Index extensions are provided as addons for each kind of supported persistence relying on the link:{quarkus_guides_base_url}/writing-extensions[Quarkus extensions] mechanism.
====

Once one of these `kogito-addons-quarkus-data-index` addons is added to a Workflow application, that service incorporates the functionality to store all the audit data and also incorporates the GraphQL endpoint to perform queries and management operations.

In the same way as the Data Index Service, there is a specific addon for each type of persistence you want to work with. Currently, we can find Data Index addons for: link:{postgresql_url}[PostgreSQL]
link:{infinispan_url}[Infinispan] and  link:{mongo_url}[MongoDB]

[IMPORTANT]
====
The `kogito-addons-quarkus-data-index` addon distribution added to the application should match with the application kind of persistence, regarding the audit data will be stored in the same database.
The addon will share the data-source used by the application where it is added, and it will create separated audit tables for that purpose.
====

When any of the data index addons is added:

* The communication with the workflow application is direct, the audit data are *not* transmitted or consumed through events, they are stored directly in the configured DB.
There is no need to configure the events connection for this purpose.
* A new GraphQL endpoint is added to perform queries and management operations

[[data-index-ext-use]]
== Adding Data Index extension to a workflow application

You can add the Data Index quarkus extension as an Addon:

.Prerequisites
* Your workflow application is working and has persistence enabled.
+
For more information about creating a workflow application, see {getting_started_create_first_workflow_guide}[Creating your first workflow service]. You also can find more details about enabling persistence in {persistence_with_postgresql_guide}[Running a workflow service using PostgreSQL]

.Procedure
. Add the required Data Index addon dependencies to the `pom.xml` file of your workflow application:
+
--
.Add Data Index Addon dependencies to `pom.xml` file
[source,xml]
----
<dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-addons-quarkus-data-index-postgresql</artifactId>
</dependency>
----

[NOTE]
====
In the example the Workflow Application is using PostgreSQL persistence, that's the reason to include the kogito-addons-quarkus-data-index-postgresql,
but this addon is distributed ready to work with other types of persistence:

* kogito-addons-quarkus-data-index-inmemory (inmemory PostgreSQL)
* kogito-addons-quarkus-data-index-postgresql
* kogito-addons-quarkus-data-index-infinispan
* kogito-addons-quarkus-data-index-mongodb
====

--

. Configure the Data Index Addon properties.
+
--
Prepare the application to run in dev mode, avoiding to start the DataIndex dev service and specify if the GraphQL UI needs to be available.

.Example adding Data Index addon properties in `application.properties` file
[source,properties]
----
<1>
  quarkus.kogito.data-index.graphql.ui.always-include=true <2>
----
<1> By default, when an application is running in dev mode, automatically a Data Index Dev Service is started and a temporary dev service Database is created.
When we are adding the addon to the application, we need to disable it by setting `quarkus.kogito.devservices.enabled` to `false`in the `application.properties` file.
<2> The addon allows to expose a simple UI to interact with the GraphQL endpoint, it only will be available when this property is set to `true`, and it will be placed in '<applicationURL>/graphql-ui/`

For more information, see `application.properties` file of link:{kogito_sw_timeouts_showcase_embedded_example_application_properties_url}[`serverless-timeouts_showcase_embedded`] example application.
--

== Additional resources

* {getting_started_create_first_workflow_guide}[Creating your first workflow service]
* {data-index-core-concepts_guide}[Data Index Core Concepts]
* {persistence_with_postgresql_guide}[Running a workflow service using PostgreSQL]

include::../../pages/_common-content/report-issue.adoc[]

