= Orchestration of gRPC based services

Learn how to invoke a gRPC service from a Kogito Serverless Workflow running with Quarkus. This guide covers:

* Creating a workflow that invokes a running gRPC service. 
* Configuring properties to locate the running service. 

== Prerequisites

It's expected that you have read the how to link:create-your-first-workflow-service.html[Create Your First Workflow] guide. 

To get familiar with gRPC concepts please visit this link:https://grpc.io/docs/what-is-grpc/core-concepts/[gRPC] link 

== Solution

In this guide, we'll go through a Serverless Workflow application that greets a user in their preferred language by invoking a gRPC service.

The application is located in the `serverless-workflow-greeting-client-rpc-quarkus`
link:https://github.com/kiegroup/kogito-examples/tree/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-client-rpc-quarkus[directory].

== Architecture

There are the following main files in this workflow application:

* link:https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-server-rpc-quarkus/src/main/proto/greeting.proto[grpc proto file]
* link:https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-client-rpc-quarkus/src/main/resources/jsongreet.sw.json[workflow definition file]
* link:https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-client-rpc-quarkus/pom.xml[Maven POM]
* link:https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-client-rpc-quarkus/src/main/resources/application.properties[Application properties]

=== gRPC proto file

This file defines a greeter service consisting of the `sayHello` method. This method accepts two parameters: the user's name and the optional language to use in the greeting message (English by default). The method returns the greeting message in the appropriate language.

----
// The greeter service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
  string language=2;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
----


=== Workflow definition file

The flow defines an RPC link:https://github.com/serverlessworkflow/specification/blob/main/specification.md#using-functions-for-rpc-service-invocations[function]. 
[source,json]
----

"functions": [
    {
      "name": "sayHello",
      "type": "rpc",
      "operation": "greeting.proto#Greeter#SayHello"
    }
  ]
----

The `operation` property is composed of three tokens separated by #: the URI of the proto file, the name of the service, and the name of the method. Kogito supports three URI schemes: `http`, `file`, and `classpath`, the latter being the default. 
Therefore, in this case, the flow declares that `greeting.proto` is expected to be found in the project classpath, that the service to be used is `Greeter` and that the method name is `sayHello` 

The flow execution consists of a single link:https://github.com/serverlessworkflow/specification/blob/main/specification.md#operation-state[operation] state, composed of one https://github.com/serverlessworkflow/specification/blob/main/specification.md#action-definition[action].

[source,json]
----
 {
    "name": "sayHello",
    "functionRef" : {
        "refName": "sayHello",
        "arguments": {
            "name": ".name",
            "language": ".language"
        }
    }
}
----

The action invokes the `sayHello` RPC method using as parameters two model variables: `name` and `language`, provided as part of the REST call that starts the flow. 
 
=== Application properties

We need to tell the application where the gRPC server is located.

[source,properties]
----
quarkus.grpc.clients.Greeter.host=localhost
quarkus.grpc.clients.Greeter.port=50051
----

Internally, the Kogito Serverless Workflow implementation uses the same set of properties as link:https://quarkus.io/guides/grpc-service-consumption#client-configuration[Quarkus gRPC client].
The "client-name" used by Kogito is the service name declared in the proto file. `Greeter` in this case.

Why is port 50051? In the same GitHub repository as the workflow application, a link:https://github.com/kiegroup/kogito-examples/tree/main/kogito-quarkus-examples/serverless-workflow-greeting-rpc-quarkus/serverless-workflow-greeting-server-rpc-quarkus[maven project] which provides a simple implementation of the greeter service is available. By default, this gRPC server runs on port 50051, hence the value for the port property. 

=== Maven POM 

gRPC functionality is included within link:https://github.com/kiegroup/kogito-runtimes/tree/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension[Serverless Workflow Quarkus extension], which means that there is no need to add specific dependencies for gRPC to work with Serverless Workflow. 
The same set of dependencies included for the Hello Workflow example will work. 

One section of the pom.xml file that needs attention is this one:

[source,xml]
----
<resource>
 <directory>${project.basedir}/../serverless-workflow-greeting-server-rpc-quarkus/src/main/proto</directory>
 <includes>
   <include>greeting.proto</include>
  </includes>
</resource>
----

Remember that the proto file, because the URI specified for it does not have any scheme, is expected to be accessible in the project's classpath. Therefore, this snippet ensures the proto file defined in the gRPC server project is included in the workflow application's classpath. 

Note that it is very unlikely you will be doing that in a real production environment. The reason is that the proto file will be either within the project directory structure (you manually copy the proto file in a directory which is included by default in the classpath) or can be downloaded from a remote server (in which case the URI will include the `http` scheme). The `file` scheme cover the cases in which proto files are stored in a shared directory which full path is known by the application. 

== Running the Application

Before running the workflow application, we need to start the gRPC server that the workflow will invoke. 

To run the gRPC server, go to the `serverless-workflow-greeting-server-rpc-quarkus` directory and execute the command:
[source, shell]
----
mvn compile exec:java -Dexec.mainClass="org.kie.kogito.examples.sw.greeting.GreeterService"
----

Then, to run the workflow application, use:

[source,shell]
----
mvn clean quarkus:dev
----

Once started, you can invoke the workflow instance with any http client, e.g. `curl`, specifying as body the name and language used in the gRPC service call.

[source,shell]
----
curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' -d '{"workflowdata" : {"name": "John", "language": "English"}}' http://localhost:8080/jsongreet
----

The response should be similar (`id` will be different for every execution) to:

[source,shell]
----
{"id":"4376cc50-42d4-45ef-8a5e-6e403a654a30","workflowdata":{"name":"John","language":"English","message":"Hello from gRPC service John"}}
----

Now, you can try greeting in a different language:

[source,shell]
----
curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' -d '{"workflowdata" : {"name": "Javi", "language": "Spanish"}}' http://localhost:8080/jsongreet
----

And enjoy the greeting in Spanish ;)
