name: SonataFlow Guides Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review, edited]
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README*"
      - "CONTRIBUTING.md"

jobs:
  build_site:
    name: "Building SonataFlow Docs with Antora"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Set environment variables
        run: |
          echo "DOCSEARCH_ENABLED=true" >> $GITHUB_ENV
          echo "DOCSEARCH_ENGINE=lunr" >> $GITHUB_ENV
          echo "NODE_PATH=$(npm -g root)" >> $GITHUB_ENV

      - name: Check Node.js version
        run: npm -v

      - name: Install dependencies and build
        run: npm run local-install-build

      - name: Publish to Surge for preview
        id: deploy
        run: npx surge ./build/site --domain https://sonataflow-docs-preview-pr-${{ github.event.number }}.surge.sh --token ${{ secrets.SURGE_LOCAL_TOKEN }}

      - name: Update PR status comment on success
        if: success()
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎊 PR Preview ${{ github.sha }} has been successfully built and deployed. See the documentation preview: https://sonataflow-docs-preview-pr-${{ github.event.number }}.surge.sh
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ github.event.number }}
          emojis: "heart"

      - name: Update PR status comment on failure
        if: failure()
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            😭 Deploy PR Preview failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ github.event.number }}
          emojis: "confused"
