#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: SonataFlow Guides Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README*"
      - "CONTRIBUTING.md"
jobs:
  build_site:
    name: "Building SonataFlow Docs with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - run: export DOCSEARCH_ENABLED=true
      - run: export DOCSEARCH_ENGINE=lunr
      - run: export NODE_PATH="$(npm -g root)"
      - run: npm -v
      - run: npm run local-install-build
  
      - name: Publishing to surge for preview
        id: deploy
        run: npx surge ./build/site --domain https://sonataflow-docs-preview-pr-${{  steps.pr.outputs.id }}.surge.sh --token ${{ secrets.SURGE_LOCAL_TOKEN }}

      - name: Update PR status comment on success
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎊 PR Preview ${{ github.sha }} has been successfully built and deployed. See the documentation preview: https://sonataflow-docs-preview-pr-${{ steps.pr.outputs.id }}.surge.sh
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}
          emojis: "heart"

      - name: Update PR status comment on failure
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            😭 Deploy PR Preview failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}
          emojis: "confused"
